# make modnpm-gen-modules > modules.inc
# MODNPM_OMITDEV=No 
# MODNPM_OMITOPTIONAL=Yes
# MODNPM_INCLUDES=
# MODNPM_EXCLUDES=
DIST_TUPLE += \
npm . 7zip-bin 5.2.0 . \
npm . acorn 8.11.3 . \
npm . acorn-jsx 5.3.2 . \
npm . acorn-walk 8.3.2 . \
npm . agent-base 6.0.2 . \
npm . ajv 6.12.6 . \
npm . ajv 8.12.0 . \
npm . ajv-formats 2.1.1 . \
npm . ajv-keywords 3.5.2 . \
npm . ansi-regex 5.0.1 . \
npm . ansi-regex 6.0.1 . \
npm . ansi-styles 3.2.1 . \
npm . ansi-styles 4.3.0 . \
npm . ansi-styles 5.2.0 . \
npm . ansi-styles 6.2.1 . \
npm . app-builder-bin 4.0.0 . \
npm . app-builder-lib 24.13.3 . \
npm . archiver 5.3.2 . \
npm . archiver-utils 2.1.0 . \
npm . archiver-utils 3.0.4 . \
npm . argparse 2.0.1 . \
npm . aria-query 5.3.0 . \
npm . array-buffer-byte-length 1.0.0 . \
npm . array-includes 3.1.7 . \
npm . array.prototype.findlastindex 1.2.3 . \
npm . array.prototype.flat 1.3.2 . \
npm . array.prototype.flatmap 1.3.2 . \
npm . array.prototype.tosorted 1.1.2 . \
npm . arraybuffer.prototype.slice 1.0.2 . \
npm . assertion-error 1.1.0 . \
npm . async 3.2.5 . \
npm . async-exit-hook 2.0.1 . \
npm . asynciterator.prototype 1.0.0 . \
npm . asynckit 0.4.0 . \
npm . at-least-node 1.0.0 . \
npm . atomically 1.7.0 . \
npm . available-typed-arrays 1.0.5 . \
npm . balanced-match 1.0.2 . \
npm . base64-js 1.5.1 . \
npm . bindings 1.5.0 . \
npm . bl 4.1.0 . \
npm . bluebird 3.7.2 . \
npm . bluebird-lst 1.0.9 . \
npm . brace-expansion 1.1.11 . \
npm . brace-expansion 2.0.1 . \
npm . browserslist 4.22.2 . \
npm . buffer 5.7.1 . \
npm . buffer-crc32 0.2.13 . \
npm . buffer-equal 1.0.1 . \
npm . buffer-from 1.1.2 . \
npm . builder-util 24.13.1 . \
npm . builder-util-runtime 9.2.4 . \
npm . builtins 5.0.1 . \
npm . cac 6.7.14 . \
npm . cacheable-lookup 5.0.4 . \
npm . cacheable-request 6.1.0 . \
npm . cacheable-request 7.0.4 . \
npm . call-bind 1.0.5 . \
npm . callsites 3.1.0 . \
npm . caniuse-lite 1.0.30001579 . \
npm . chai 4.4.1 . \
npm . chalk 2.4.2 . \
npm . chalk 4.1.2 . \
npm . check-error 1.0.3 . \
npm . chownr 1.1.4 . \
npm . chownr 2.0.0 . \
npm . chrome-launcher 0.15.2 . \
npm . chromium-pickle-js 0.2.0 . \
npm . ci-info 3.9.0 . \
npm . cliui 8.0.1 . \
npm . clone-response 1.0.3 . \
npm . color-convert 1.9.3 . \
npm . color-convert 2.0.1 . \
npm . color-name 1.1.3 . \
npm . color-name 1.1.4 . \
npm . combined-stream 1.0.8 . \
npm . commander 5.1.0 . \
npm . compare-version 0.1.2 . \
npm . compress-commons 4.1.2 . \
npm . concat-map 0.0.1 . \
npm . conf 10.2.0 . \
npm . config-file-ts 0.2.6 . \
npm . convert-source-map 2.0.0 . \
npm . core-util-is 1.0.2 . \
npm . crc-32 1.2.2 . \
npm . crc32-stream 4.0.3 . \
npm . cross-env 7.0.3 . \
npm . cross-fetch 3.1.5 . \
npm . cross-spawn 7.0.3 . \
npm . css-shorthand-properties 1.1.1 . \
npm . css-value 0.0.1 . \
npm . debounce-fn 4.0.0 . \
npm . debug 2.6.9 . \
npm . debug 3.2.7 . \
npm . debug 4.3.4 . \
npm . decompress-response 3.3.0 . \
npm . decompress-response 6.0.0 . \
npm . deep-eql 4.1.3 . \
npm . deep-is 0.1.4 . \
npm . deepmerge 4.3.1 . \
npm . defer-to-connect 1.1.3 . \
npm . defer-to-connect 2.0.1 . \
npm . define-data-property 1.1.1 . \
npm . define-properties 1.2.1 . \
npm . delayed-stream 1.0.0 . \
npm . dequal 2.0.3 . \
npm . dev-null 0.1.1 . \
npm . devtools 7.16.13 . \
npm . devtools-protocol 0.0.953906 . \
npm . devtools-protocol 0.0.981744 . \
npm . diff-sequences 29.6.3 . \
npm . dir-compare 3.3.0 . \
npm . dmg-builder 24.13.3 . \
npm . doctrine 2.1.0 . \
npm . doctrine 3.0.0 . \
npm . dot-prop 6.0.1 . \
npm . dotenv 9.0.2 . \
npm . dotenv-expand 5.1.0 . \
npm . duplexer 0.1.2 . \
npm . duplexer3 0.1.5 . \
npm . eastasianwidth 0.2.0 . \
npm . edge-paths 2.2.1 . \
npm . ejs 3.1.9 . \
npm . electron 28.1.4 . \
npm . electron-builder 24.13.3 . \
npm . electron-builder-squirrel-windows 24.13.3 . \
npm . electron-chromedriver 17.0.0 . \
npm . electron-log 5.0.3 . \
npm . electron-publish 24.13.1 . \
npm . electron-store 8.1.0 . \
npm . electron-to-chromium 1.4.640 . \
npm . emoji-regex 8.0.0 . \
npm . emoji-regex 9.2.2 . \
npm . end-of-stream 1.4.4 . \
npm . env-paths 2.2.1 . \
npm . err-code 2.0.3 . \
npm . error-ex 1.3.2 . \
npm . es-abstract 1.22.3 . \
npm . es-iterator-helpers 1.0.15 . \
npm . es-set-tostringtag 2.0.2 . \
npm . es-shim-unscopables 1.0.2 . \
npm . es-to-primitive 1.2.1 . \
npm . esbuild 0.19.11 . \
npm . escalade 3.1.1 . \
npm . escape-string-regexp 1.0.5 . \
npm . escape-string-regexp 4.0.0 . \
npm . eslint 8.56.0 . \
npm . eslint-config-standard 17.1.0 . \
npm . eslint-config-standard-jsx 11.0.0 . \
npm . eslint-import-resolver-node 0.3.9 . \
npm . eslint-module-utils 2.8.0 . \
npm . eslint-plugin-es 4.1.0 . \
npm . eslint-plugin-import 2.29.1 . \
npm . eslint-plugin-n 15.7.0 . \
npm . eslint-plugin-promise 6.1.1 . \
npm . eslint-plugin-react 7.33.2 . \
npm . eslint-scope 7.2.2 . \
npm . eslint-utils 2.1.0 . \
npm . eslint-utils 3.0.0 . \
npm . eslint-visitor-keys 1.3.0 . \
npm . eslint-visitor-keys 2.1.0 . \
npm . eslint-visitor-keys 3.4.3 . \
npm . espree 9.6.1 . \
npm . esquery 1.5.0 . \
npm . esrecurse 4.3.0 . \
npm . estraverse 5.3.0 . \
npm . estree-walker 3.0.3 . \
npm . esutils 2.0.3 . \
npm . event-stream 4.0.1 . \
npm . execa 8.0.1 . \
npm . extract-zip 2.0.1 . \
npm . fast-deep-equal 2.0.1 . \
npm . fast-deep-equal 3.1.3 . \
npm . fast-json-stable-stringify 2.1.0 . \
npm . fast-levenshtein 2.0.6 . \
npm . fastq 1.16.0 . \
npm . fd-slicer 1.1.0 . \
npm . file-entry-cache 6.0.1 . \
npm . file-uri-to-path 1.0.0 . \
npm . filelist 1.0.4 . \
npm . find-up 3.0.0 . \
npm . find-up 4.1.0 . \
npm . find-up 5.0.0 . \
npm . flat-cache 3.2.0 . \
npm . flatted 3.2.9 . \
npm . for-each 0.3.3 . \
npm . foreground-child 3.1.1 . \
npm . form-data 4.0.0 . \
npm . from 0.1.7 . \
npm . fs-constants 1.0.0 . \
npm . fs-extra 10.1.0 . \
npm . fs-extra 8.1.0 . \
npm . fs-extra 9.1.0 . \
npm . fs-minipass 2.1.0 . \
npm . fs.realpath 1.0.0 . \
npm . function-bind 1.1.2 . \
npm . function.prototype.name 1.1.6 . \
npm . functions-have-names 1.2.3 . \
npm . gensync 1.0.0-beta.2 . \
npm . get-caller-file 2.0.5 . \
npm . get-func-name 2.0.2 . \
npm . get-intrinsic 1.2.2 . \
npm . get-port 5.1.1 . \
npm . get-stdin 8.0.0 . \
npm . get-stream 4.1.0 . \
npm . get-stream 5.2.0 . \
npm . get-stream 8.0.1 . \
npm . get-symbol-description 1.0.0 . \
npm . glob 10.3.10 . \
npm . glob 7.2.3 . \
npm . glob-parent 6.0.2 . \
npm . globals 11.12.0 . \
npm . globals 13.24.0 . \
npm . globalthis 1.0.3 . \
npm . gopd 1.0.1 . \
npm . got 11.8.6 . \
npm . got 9.6.0 . \
npm . graceful-fs 4.2.11 . \
npm . grapheme-splitter 1.0.4 . \
npm . graphemer 1.4.0 . \
npm . has-bigints 1.0.2 . \
npm . has-flag 3.0.0 . \
npm . has-flag 4.0.0 . \
npm . has-property-descriptors 1.0.1 . \
npm . has-proto 1.0.1 . \
npm . has-symbols 1.0.3 . \
npm . has-tostringtag 1.0.0 . \
npm . hasown 2.0.0 . \
npm . hosted-git-info 4.1.0 . \
npm . html-escaper 2.0.2 . \
npm . http-cache-semantics 4.1.1 . \
npm . http-proxy-agent 5.0.0 . \
npm . http2-wrapper 1.0.3 . \
npm . https-proxy-agent 5.0.1 . \
npm . human-signals 5.0.0 . \
npm . humanize-duration 3.31.0 . \
npm . husky 8.0.3 . \
npm . i18next 23.7.18 . \
npm . i18next-fs-backend 2.3.1 . \
npm . iconv-lite 0.6.3 . \
npm . ieee754 1.2.1 . \
npm . ignore 5.3.0 . \
npm . import-fresh 3.3.0 . \
npm . imurmurhash 0.1.4 . \
npm . inflight 1.0.6 . \
npm . inherits 2.0.4 . \
npm . internal-slot 1.0.6 . \
npm . is-array-buffer 3.0.2 . \
npm . is-arrayish 0.2.1 . \
npm . is-async-function 2.0.0 . \
npm . is-bigint 1.0.4 . \
npm . is-boolean-object 1.1.2 . \
npm . is-callable 1.2.7 . \
npm . is-ci 3.0.1 . \
npm . is-core-module 2.13.1 . \
npm . is-date-object 1.0.5 . \
npm . is-docker 2.2.1 . \
npm . is-extglob 2.1.1 . \
npm . is-finalizationregistry 1.0.2 . \
npm . is-fullwidth-code-point 3.0.0 . \
npm . is-generator-function 1.0.10 . \
npm . is-glob 4.0.3 . \
npm . is-map 2.0.2 . \
npm . is-negative-zero 2.0.2 . \
npm . is-number-object 1.0.7 . \
npm . is-obj 2.0.0 . \
npm . is-path-inside 3.0.3 . \
npm . is-regex 1.1.4 . \
npm . is-set 2.0.2 . \
npm . is-shared-array-buffer 1.0.2 . \
npm . is-stream 3.0.0 . \
npm . is-string 1.0.7 . \
npm . is-symbol 1.0.4 . \
npm . is-typed-array 1.1.12 . \
npm . is-weakmap 2.0.1 . \
npm . is-weakref 1.0.2 . \
npm . is-weakset 2.0.2 . \
npm . is-wsl 2.2.0 . \
npm . isarray 1.0.0 . \
npm . isarray 2.0.5 . \
npm . isbinaryfile 4.0.10 . \
npm . isbinaryfile 5.0.2 . \
npm . isexe 2.0.0 . \
npm . istanbul-lib-coverage 3.2.2 . \
npm . istanbul-lib-instrument 6.0.1 . \
npm . istanbul-lib-report 3.0.1 . \
npm . istanbul-lib-source-maps 4.0.1 . \
npm . istanbul-reports 3.1.6 . \
npm . iterator.prototype 1.1.2 . \
npm . jackspeak 2.3.6 . \
npm . jake 10.8.7 . \
npm . js-tokens 4.0.0 . \
npm . js-yaml 4.1.0 . \
npm . jsesc 2.5.2 . \
npm . json-buffer 3.0.0 . \
npm . json-buffer 3.0.1 . \
npm . json-parse-better-errors 1.0.2 . \
npm . json-schema-traverse 0.4.1 . \
npm . json-schema-traverse 1.0.0 . \
npm . json-schema-typed 7.0.3 . \
npm . json-stable-stringify-without-jsonify 1.0.1 . \
npm . json5 1.0.2 . \
npm . json5 2.2.3 . \
npm . jsonc-parser 3.2.0 . \
npm . jsonfile 4.0.0 . \
npm . jsonfile 6.1.0 . \
npm . jsx-ast-utils 3.3.5 . \
npm . keyv 3.1.0 . \
npm . keyv 4.5.4 . \
npm . ky 0.28.7 . \
npm . lazy-val 1.0.5 . \
npm . lazystream 1.0.1 . \
npm . levn 0.4.1 . \
npm . lighthouse-logger 1.4.2 . \
npm . load-json-file 5.3.0 . \
npm . local-pkg 0.5.0 . \
npm . locate-path 3.0.0 . \
npm . locate-path 5.0.0 . \
npm . locate-path 6.0.0 . \
npm . lodash 4.17.21 . \
npm . lodash.clonedeep 4.5.0 . \
npm . lodash.defaults 4.2.0 . \
npm . lodash.difference 4.5.0 . \
npm . lodash.flatten 4.4.0 . \
npm . lodash.isobject 3.0.2 . \
npm . lodash.isplainobject 4.0.6 . \
npm . lodash.merge 4.6.2 . \
npm . lodash.union 4.6.0 . \
npm . lodash.zip 4.2.0 . \
npm . loglevel 1.8.1 . \
npm . loglevel-plugin-prefix 0.8.4 . \
npm . long 5.2.1 . \
npm . loose-envify 1.4.0 . \
npm . loupe 2.3.7 . \
npm . lowercase-keys 1.0.1 . \
npm . lowercase-keys 2.0.0 . \
npm . lru-cache 10.1.0 . \
npm . lru-cache 5.1.1 . \
npm . lru-cache 6.0.0 . \
npm . luxon 1.28.1 . \
npm . luxon 3.4.4 . \
npm . macos-notification-state 3.0.0 . \
npm . magic-string 0.30.5 . \
npm . magicast 0.3.3 . \
npm . make-dir 4.0.0 . \
npm . map-stream 0.0.7 . \
npm . marky 1.2.5 . \
npm . meeussunmoon 3.0.3 . \
npm . merge-stream 2.0.0 . \
npm . mime 2.6.0 . \
npm . mime-db 1.52.0 . \
npm . mime-types 2.1.35 . \
npm . mimic-fn 2.1.0 . \
npm . mimic-fn 3.1.0 . \
npm . mimic-fn 4.0.0 . \
npm . mimic-response 1.0.1 . \
npm . mimic-response 3.1.0 . \
npm . minimatch 3.1.2 . \
npm . minimatch 5.1.6 . \
npm . minimatch 9.0.3 . \
npm . minimist 1.2.8 . \
npm . minipass 3.3.6 . \
npm . minipass 5.0.0 . \
npm . minizlib 2.1.2 . \
npm . mkdirp 1.0.4 . \
npm . mkdirp-classic 0.5.3 . \
npm . mlly 1.5.0 . \
npm . ms 2.0.0 . \
npm . ms 2.1.2 . \
npm . nanoid 3.3.7 . \
npm . natural-compare 1.4.0 . \
npm . node-addon-api 1.7.2 . \
npm . node-addon-api 3.0.0 . \
npm . node-fetch 2.6.7 . \
npm . node-releases 2.0.14 . \
npm . normalize-path 3.0.0 . \
npm . normalize-url 4.5.1 . \
npm . normalize-url 6.1.0 . \
npm . npm-run-path 5.2.0 . \
npm . object-assign 4.1.1 . \
npm . object-inspect 1.13.1 . \
npm . object-keys 1.1.1 . \
npm . object.assign 4.1.5 . \
npm . object.entries 1.1.7 . \
npm . object.fromentries 2.0.7 . \
npm . object.groupby 1.0.1 . \
npm . object.hasown 1.1.3 . \
npm . object.values 1.1.7 . \
npm . once 1.4.0 . \
npm . onetime 5.1.2 . \
npm . onetime 6.0.0 . \
npm . optionator 0.9.3 . \
npm . p-cancelable 1.1.0 . \
npm . p-cancelable 2.1.1 . \
npm . p-iteration 1.1.8 . \
npm . p-limit 2.3.0 . \
npm . p-limit 3.1.0 . \
npm . p-limit 5.0.0 . \
npm . p-locate 3.0.0 . \
npm . p-locate 4.1.0 . \
npm . p-locate 5.0.0 . \
npm . p-try 2.2.0 . \
npm . parent-module 1.0.1 . \
npm . parse-json 4.0.0 . \
npm . path-exists 3.0.0 . \
npm . path-exists 4.0.0 . \
npm . path-is-absolute 1.0.1 . \
npm . path-key 3.1.1 . \
npm . path-key 4.0.0 . \
npm . path-parse 1.0.7 . \
npm . path-scurry 1.10.1 . \
npm . pathe 1.1.2 . \
npm . pathval 1.1.1 . \
npm . pause-stream 0.0.11 . \
npm . pend 1.2.0 . \
npm . picocolors 1.0.0 . \
npm . pify 4.0.1 . \
npm . pkg-conf 3.1.0 . \
npm . pkg-dir 4.2.0 . \
npm . pkg-types 1.0.3 . \
npm . pkg-up 3.1.0 . \
npm . plist 3.1.0 . \
npm . postcss 8.4.33 . \
npm . prelude-ls 1.2.1 . \
npm . prepend-http 2.0.0 . \
npm . pretty-format 29.7.0 . \
npm . process-nextick-args 2.0.1 . \
npm . progress 2.0.3 . \
npm . promise-retry 2.0.1 . \
npm . prop-types 15.8.1 . \
npm . proxy-from-env 1.1.0 . \
npm . ps-list 7.2.0 . \
npm . pump 3.0.0 . \
npm . punycode 2.3.1 . \
npm . puppeteer-core 13.7.0 . \
npm . query-selector-shadow-dom 1.0.1 . \
npm . queue-microtask 1.2.3 . \
npm . quick-lru 5.1.1 . \
npm . react-is 16.13.1 . \
npm . react-is 18.2.0 . \
npm . read-config-file 6.3.2 . \
npm . readable-stream 2.3.8 . \
npm . readable-stream 3.6.2 . \
npm . readdir-glob 1.1.3 . \
npm . reflect.getprototypeof 1.0.4 . \
npm . regenerator-runtime 0.14.1 . \
npm . regexp.prototype.flags 1.5.1 . \
npm . regexpp 3.2.0 . \
npm . require-directory 2.1.1 . \
npm . require-from-string 2.0.2 . \
npm . resolve 1.22.8 . \
npm . resolve 2.0.0-next.5 . \
npm . resolve-alpn 1.2.1 . \
npm . resolve-from 4.0.0 . \
npm . responselike 1.0.2 . \
npm . responselike 2.0.1 . \
npm . resq 1.11.0 . \
npm . retry 0.12.0 . \
npm . reusify 1.0.4 . \
npm . rgb2hex 0.2.5 . \
npm . rimraf 3.0.2 . \
npm . rimraf 5.0.5 . \
npm . rollup 4.9.6 . \
npm . rtl-detect 1.1.2 . \
npm . run-parallel 1.2.0 . \
npm . safe-array-concat 1.1.0 . \
npm . safe-buffer 5.1.2 . \
npm . safe-buffer 5.2.1 . \
npm . safe-regex-test 1.0.2 . \
npm . safer-buffer 2.1.2 . \
npm . sanitize-filename 1.6.3 . \
npm . sax 1.3.0 . \
npm . semver 6.3.1 . \
npm . semver 7.5.4 . \
npm . serialize-error 8.1.0 . \
npm . set-function-length 1.2.0 . \
npm . set-function-name 2.0.1 . \
npm . shebang-command 2.0.0 . \
npm . shebang-regex 3.0.0 . \
npm . side-channel 1.0.4 . \
npm . siginfo 2.0.0 . \
npm . signal-exit 4.1.0 . \
npm . simple-update-notifier 2.0.0 . \
npm . source-map 0.6.1 . \
npm . source-map-js 1.0.2 . \
npm . source-map-support 0.5.21 . \
npm . spectron 19.0.0 . \
npm . split 1.0.1 . \
npm . stackback 0.0.2 . \
npm . standard 17.1.0 . \
npm . standard-engine 15.1.0 . \
npm . stat-mode 1.0.0 . \
npm . std-env 3.7.0 . \
npm . stream-combiner 0.2.2 . \
npm . string-width 4.2.3 . \
npm . string-width 5.1.2 . \
npm . string.prototype.matchall 4.0.10 . \
npm . string.prototype.trim 1.2.8 . \
npm . string.prototype.trimend 1.0.7 . \
npm . string.prototype.trimstart 1.0.7 . \
npm . string_decoder 1.1.1 . \
npm . string_decoder 1.3.0 . \
npm . strip-ansi 6.0.1 . \
npm . strip-ansi 7.1.0 . \
npm . strip-bom 3.0.0 . \
npm . strip-final-newline 3.0.0 . \
npm . strip-json-comments 3.1.1 . \
npm . strip-literal 1.3.0 . \
npm . sumchecker 3.0.1 . \
npm . supports-color 5.5.0 . \
npm . supports-color 7.2.0 . \
npm . supports-preserve-symlinks-flag 1.0.0 . \
npm . tar 6.2.0 . \
npm . tar-fs 2.1.1 . \
npm . tar-stream 2.2.0 . \
npm . temp-file 3.4.0 . \
npm . test-exclude 6.0.0 . \
npm . text-table 0.2.0 . \
npm . through 2.3.8 . \
npm . tinybench 2.6.0 . \
npm . tinypool 0.8.2 . \
npm . tinyspy 2.2.0 . \
npm . tmp 0.2.3 . \
npm . tmp-promise 3.0.3 . \
npm . to-fast-properties 2.0.0 . \
npm . to-readable-stream 1.0.0 . \
npm . tr46 0.0.3 . \
npm . truncate-utf8-bytes 1.0.2 . \
npm . tsconfig-paths 3.15.0 . \
npm . type-check 0.4.0 . \
npm . type-detect 4.0.8 . \
npm . type-fest 0.20.2 . \
npm . type-fest 0.3.1 . \
npm . type-fest 2.19.0 . \
npm . typed-array-buffer 1.0.0 . \
npm . typed-array-byte-length 1.0.0 . \
npm . typed-array-byte-offset 1.0.0 . \
npm . typed-array-length 1.0.4 . \
npm . typescript 5.3.3 . \
npm . ua-parser-js 1.0.37 . \
npm . ufo 1.3.2 . \
npm . unbox-primitive 1.0.2 . \
npm . unbzip2-stream 1.4.3 . \
npm . undici-types 5.26.5 . \
npm . universalify 0.1.2 . \
npm . universalify 2.0.1 . \
npm . update-browserslist-db 1.0.13 . \
npm . uri-js 4.4.1 . \
npm . url-parse-lax 3.0.0 . \
npm . utf8-byte-length 1.0.4 . \
npm . util-deprecate 1.0.2 . \
npm . uuid 8.3.2 . \
npm . version-guard 1.1.1 . \
npm . vite 5.0.12 . \
npm . vite-node 1.2.1 . \
npm . vitest 1.2.1 . \
npm . webdriver 7.16.13 . \
npm . webdriverio 7.16.13 . \
npm . webidl-conversions 3.0.1 . \
npm . whatwg-url 5.0.0 . \
npm . which 2.0.2 . \
npm . which-boxed-primitive 1.0.2 . \
npm . which-builtin-type 1.1.3 . \
npm . which-collection 1.0.1 . \
npm . which-typed-array 1.1.13 . \
npm . why-is-node-running 2.2.2 . \
npm . windows-focus-assist 1.3.0 . \
npm . windows-quiet-hours 2.0.0 . \
npm . wrap-ansi 7.0.0 . \
npm . wrap-ansi 8.1.0 . \
npm . wrappy 1.0.2 . \
npm . ws 8.5.0 . \
npm . xdg-basedir 4.0.0 . \
npm . xml2js 0.5.0 . \
npm . xmlbuilder 11.0.1 . \
npm . xmlbuilder 15.1.1 . \
npm . y18n 5.0.8 . \
npm . yallist 3.1.1 . \
npm . yallist 4.0.0 . \
npm . yargs 17.7.2 . \
npm . yargs-parser 21.1.1 . \
npm . yauzl 2.10.0 . \
npm . yocto-queue 0.1.0 . \
npm . yocto-queue 1.0.0 . \
npm . zip-stream 4.1.1 . \
npm @aashutoshrathi word-wrap 1.2.6 . \
npm @ampproject remapping 2.2.1 . \
npm @babel code-frame 7.23.5 . \
npm @babel compat-data 7.23.5 . \
npm @babel core 7.23.7 . \
npm @babel generator 7.23.6 . \
npm @babel helper-compilation-targets 7.23.6 . \
npm @babel helper-environment-visitor 7.22.20 . \
npm @babel helper-function-name 7.23.0 . \
npm @babel helper-hoist-variables 7.22.5 . \
npm @babel helper-module-imports 7.22.15 . \
npm @babel helper-module-transforms 7.23.3 . \
npm @babel helper-simple-access 7.22.5 . \
npm @babel helper-split-export-declaration 7.22.6 . \
npm @babel helper-string-parser 7.23.4 . \
npm @babel helper-validator-identifier 7.22.20 . \
npm @babel helper-validator-option 7.23.5 . \
npm @babel helpers 7.23.8 . \
npm @babel highlight 7.23.4 . \
npm @babel parser 7.23.6 . \
npm @babel runtime 7.23.8 . \
npm @babel template 7.22.15 . \
npm @babel traverse 7.23.7 . \
npm @babel types 7.23.6 . \
npm @develar schema-utils 2.6.5 . \
npm @electron asar 3.2.8 . \
npm @electron get 1.14.1 . \
npm @electron get 2.0.3 . \
npm @electron notarize 2.2.1 . \
npm @electron osx-sign 1.0.5 . \
npm @electron remote 2.0.4 . \
npm @electron remote 2.1.1 . \
npm @electron universal 1.5.1 . \
npm @eslint eslintrc 2.1.4 . \
npm @eslint js 8.56.0 . \
npm @eslint-community eslint-utils 4.4.0 . \
npm @eslint-community regexpp 4.10.0 . \
npm @humanwhocodes config-array 0.11.14 . \
npm @humanwhocodes module-importer 1.0.1 . \
npm @humanwhocodes object-schema 2.0.2 . \
npm @isaacs cliui 8.0.2 . \
npm @istanbuljs schema 0.1.3 . \
npm @jest schemas 29.6.3 . \
npm @jridgewell gen-mapping 0.3.3 . \
npm @jridgewell resolve-uri 3.1.1 . \
npm @jridgewell set-array 1.1.2 . \
npm @jridgewell sourcemap-codec 1.4.15 . \
npm @jridgewell trace-mapping 0.3.22 . \
npm @malept cross-spawn-promise 1.1.1 . \
npm @malept flatpak-bundler 0.4.0 . \
npm @nodelib fs.scandir 2.1.5 . \
npm @nodelib fs.stat 2.0.5 . \
npm @nodelib fs.walk 1.2.8 . \
npm @nornagon put 0.0.8 . \
npm @sinclair typebox 0.27.8 . \
npm @sindresorhus is 0.14.0 . \
npm @sindresorhus is 4.6.0 . \
npm @szmarczak http-timer 1.1.2 . \
npm @szmarczak http-timer 4.0.6 . \
npm @tootallnate once 2.0.0 . \
npm @types aria-query 5.0.4 . \
npm @types cacheable-request 6.0.3 . \
npm @types debug 4.1.12 . \
npm @types estree 1.0.5 . \
npm @types fs-extra 9.0.13 . \
npm @types http-cache-semantics 4.0.4 . \
npm @types json5 0.0.29 . \
npm @types keyv 3.1.4 . \
npm @types ms 0.7.34 . \
npm @types node 17.0.45 . \
npm @types node 18.19.8 . \
npm @types responselike 1.0.3 . \
npm @types ua-parser-js 0.7.39 . \
npm @types which 1.3.2 . \
npm @ungap structured-clone 1.2.0 . \
npm @vitest coverage-istanbul 1.2.1 . \
npm @vitest expect 1.2.1 . \
npm @vitest runner 1.2.1 . \
npm @vitest snapshot 1.2.1 . \
npm @vitest spy 1.2.1 . \
npm @vitest utils 1.2.1 . \
npm @wdio config 7.16.13 . \
npm @wdio logger 7.16.0 . \
npm @wdio protocols 7.16.7 . \
npm @wdio repl 7.16.13 . \
npm @wdio types 7.16.13 . \
npm @wdio utils 7.16.13 . \
npm @xmldom xmldom 0.8.10 . \

MODNPM_CP += \
/node_modules/zip-stream;.-zip-stream-4.1.1 \
/node_modules/zip-stream/node_modules/archiver-utils;.-archiver-utils-3.0.4 \
/node_modules/yocto-queue;.-yocto-queue-1.0.0 \
/node_modules/yauzl;.-yauzl-2.10.0 \
/node_modules/yargs;.-yargs-17.7.2 \
/node_modules/yargs-parser;.-yargs-parser-21.1.1 \
/node_modules/yallist;.-yallist-4.0.0 \
/node_modules/y18n;.-y18n-5.0.8 \
/node_modules/xmlbuilder;.-xmlbuilder-15.1.1 \
/node_modules/xml2js;.-xml2js-0.5.0 \
/node_modules/xml2js/node_modules/xmlbuilder;.-xmlbuilder-11.0.1 \
/node_modules/xdg-basedir;.-xdg-basedir-4.0.0 \
/node_modules/ws;.-ws-8.5.0 \
/node_modules/wrappy;.-wrappy-1.0.2 \
/node_modules/wrap-ansi;.-wrap-ansi-7.0.0 \
/node_modules/wrap-ansi-cjs;.-wrap-ansi-7.0.0 \
/node_modules/windows-quiet-hours;.-windows-quiet-hours-2.0.0 \
/node_modules/windows-focus-assist;.-windows-focus-assist-1.3.0 \
/node_modules/why-is-node-running;.-why-is-node-running-2.2.2 \
/node_modules/which;.-which-2.0.2 \
/node_modules/which-typed-array;.-which-typed-array-1.1.13 \
/node_modules/which-collection;.-which-collection-1.0.1 \
/node_modules/which-builtin-type;.-which-builtin-type-1.1.3 \
/node_modules/which-boxed-primitive;.-which-boxed-primitive-1.0.2 \
/node_modules/whatwg-url;.-whatwg-url-5.0.0 \
/node_modules/webidl-conversions;.-webidl-conversions-3.0.1 \
/node_modules/webdriverio;.-webdriverio-7.16.13 \
/node_modules/webdriverio/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/webdriverio/node_modules/type-fest;.-type-fest-0.20.2 \
/node_modules/webdriverio/node_modules/serialize-error;.-serialize-error-8.1.0 \
/node_modules/webdriverio/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/webdriverio/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/webdriverio/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/webdriverio/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/webdriverio/node_modules/@types/node;@types-node-17.0.45 \
/node_modules/webdriver;.-webdriver-7.16.13 \
/node_modules/webdriver/node_modules/@types/node;@types-node-17.0.45 \
/node_modules/vitest;.-vitest-1.2.1 \
/node_modules/vite;.-vite-5.0.12 \
/node_modules/vite-node;.-vite-node-1.2.1 \
/node_modules/version-guard;.-version-guard-1.1.1 \
/node_modules/uuid;.-uuid-8.3.2 \
/node_modules/util-deprecate;.-util-deprecate-1.0.2 \
/node_modules/utf8-byte-length;.-utf8-byte-length-1.0.4 \
/node_modules/url-parse-lax;.-url-parse-lax-3.0.0 \
/node_modules/uri-js;.-uri-js-4.4.1 \
/node_modules/update-browserslist-db;.-update-browserslist-db-1.0.13 \
/node_modules/universalify;.-universalify-0.1.2 \
/node_modules/undici-types;.-undici-types-5.26.5 \
/node_modules/unbzip2-stream;.-unbzip2-stream-1.4.3 \
/node_modules/unbox-primitive;.-unbox-primitive-1.0.2 \
/node_modules/ufo;.-ufo-1.3.2 \
/node_modules/ua-parser-js;.-ua-parser-js-1.0.37 \
/node_modules/typescript;.-typescript-5.3.3 \
/node_modules/typed-array-length;.-typed-array-length-1.0.4 \
/node_modules/typed-array-byte-offset;.-typed-array-byte-offset-1.0.0 \
/node_modules/typed-array-byte-length;.-typed-array-byte-length-1.0.0 \
/node_modules/typed-array-buffer;.-typed-array-buffer-1.0.0 \
/node_modules/type-fest;.-type-fest-2.19.0 \
/node_modules/type-detect;.-type-detect-4.0.8 \
/node_modules/type-check;.-type-check-0.4.0 \
/node_modules/tsconfig-paths;.-tsconfig-paths-3.15.0 \
/node_modules/tsconfig-paths/node_modules/json5;.-json5-1.0.2 \
/node_modules/truncate-utf8-bytes;.-truncate-utf8-bytes-1.0.2 \
/node_modules/tr46;.-tr46-0.0.3 \
/node_modules/to-readable-stream;.-to-readable-stream-1.0.0 \
/node_modules/to-fast-properties;.-to-fast-properties-2.0.0 \
/node_modules/tmp;.-tmp-0.2.3 \
/node_modules/tmp-promise;.-tmp-promise-3.0.3 \
/node_modules/tinyspy;.-tinyspy-2.2.0 \
/node_modules/tinypool;.-tinypool-0.8.2 \
/node_modules/tinybench;.-tinybench-2.6.0 \
/node_modules/through;.-through-2.3.8 \
/node_modules/text-table;.-text-table-0.2.0 \
/node_modules/test-exclude;.-test-exclude-6.0.0 \
/node_modules/test-exclude/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/test-exclude/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/temp-file;.-temp-file-3.4.0 \
/node_modules/temp-file/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/temp-file/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/temp-file/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/tar;.-tar-6.2.0 \
/node_modules/tar-stream;.-tar-stream-2.2.0 \
/node_modules/tar-fs;.-tar-fs-2.1.1 \
/node_modules/tar-fs/node_modules/chownr;.-chownr-1.1.4 \
/node_modules/supports-preserve-symlinks-flag;.-supports-preserve-symlinks-flag-1.0.0 \
/node_modules/supports-color;.-supports-color-7.2.0 \
/node_modules/sumchecker;.-sumchecker-3.0.1 \
/node_modules/strip-literal;.-strip-literal-1.3.0 \
/node_modules/strip-json-comments;.-strip-json-comments-3.1.1 \
/node_modules/strip-final-newline;.-strip-final-newline-3.0.0 \
/node_modules/strip-bom;.-strip-bom-3.0.0 \
/node_modules/strip-ansi;.-strip-ansi-6.0.1 \
/node_modules/strip-ansi-cjs;.-strip-ansi-6.0.1 \
/node_modules/string_decoder;.-string_decoder-1.3.0 \
/node_modules/string.prototype.trimstart;.-string.prototype.trimstart-1.0.7 \
/node_modules/string.prototype.trimend;.-string.prototype.trimend-1.0.7 \
/node_modules/string.prototype.trim;.-string.prototype.trim-1.2.8 \
/node_modules/string.prototype.matchall;.-string.prototype.matchall-4.0.10 \
/node_modules/string-width;.-string-width-4.2.3 \
/node_modules/string-width-cjs;.-string-width-4.2.3 \
/node_modules/stream-combiner;.-stream-combiner-0.2.2 \
/node_modules/std-env;.-std-env-3.7.0 \
/node_modules/stat-mode;.-stat-mode-1.0.0 \
/node_modules/standard;.-standard-17.1.0 \
/node_modules/standard-engine;.-standard-engine-15.1.0 \
/node_modules/stackback;.-stackback-0.0.2 \
/node_modules/split;.-split-1.0.1 \
/node_modules/spectron;.-spectron-19.0.0 \
/node_modules/spectron/node_modules/@electron/remote;@electron-remote-2.0.4 \
/node_modules/source-map;.-source-map-0.6.1 \
/node_modules/source-map-support;.-source-map-support-0.5.21 \
/node_modules/source-map-js;.-source-map-js-1.0.2 \
/node_modules/simple-update-notifier;.-simple-update-notifier-2.0.0 \
/node_modules/signal-exit;.-signal-exit-4.1.0 \
/node_modules/siginfo;.-siginfo-2.0.0 \
/node_modules/side-channel;.-side-channel-1.0.4 \
/node_modules/shebang-regex;.-shebang-regex-3.0.0 \
/node_modules/shebang-command;.-shebang-command-2.0.0 \
/node_modules/set-function-name;.-set-function-name-2.0.1 \
/node_modules/set-function-length;.-set-function-length-1.2.0 \
/node_modules/semver;.-semver-7.5.4 \
/node_modules/sax;.-sax-1.3.0 \
/node_modules/sanitize-filename;.-sanitize-filename-1.6.3 \
/node_modules/safer-buffer;.-safer-buffer-2.1.2 \
/node_modules/safe-regex-test;.-safe-regex-test-1.0.2 \
/node_modules/safe-buffer;.-safe-buffer-5.2.1 \
/node_modules/safe-array-concat;.-safe-array-concat-1.1.0 \
/node_modules/run-parallel;.-run-parallel-1.2.0 \
/node_modules/rtl-detect;.-rtl-detect-1.1.2 \
/node_modules/rollup;.-rollup-4.9.6 \
/node_modules/rimraf;.-rimraf-5.0.5 \
/node_modules/rimraf/node_modules/minimatch;.-minimatch-9.0.3 \
/node_modules/rimraf/node_modules/glob;.-glob-10.3.10 \
/node_modules/rgb2hex;.-rgb2hex-0.2.5 \
/node_modules/reusify;.-reusify-1.0.4 \
/node_modules/retry;.-retry-0.12.0 \
/node_modules/resq;.-resq-1.11.0 \
/node_modules/resq/node_modules/fast-deep-equal;.-fast-deep-equal-2.0.1 \
/node_modules/responselike;.-responselike-2.0.1 \
/node_modules/resolve;.-resolve-1.22.8 \
/node_modules/resolve-from;.-resolve-from-4.0.0 \
/node_modules/resolve-alpn;.-resolve-alpn-1.2.1 \
/node_modules/require-from-string;.-require-from-string-2.0.2 \
/node_modules/require-directory;.-require-directory-2.1.1 \
/node_modules/regexpp;.-regexpp-3.2.0 \
/node_modules/regexp.prototype.flags;.-regexp.prototype.flags-1.5.1 \
/node_modules/regenerator-runtime;.-regenerator-runtime-0.14.1 \
/node_modules/reflect.getprototypeof;.-reflect.getprototypeof-1.0.4 \
/node_modules/readdir-glob;.-readdir-glob-1.1.3 \
/node_modules/readable-stream;.-readable-stream-3.6.2 \
/node_modules/read-config-file;.-read-config-file-6.3.2 \
/node_modules/react-is;.-react-is-16.13.1 \
/node_modules/quick-lru;.-quick-lru-5.1.1 \
/node_modules/queue-microtask;.-queue-microtask-1.2.3 \
/node_modules/query-selector-shadow-dom;.-query-selector-shadow-dom-1.0.1 \
/node_modules/puppeteer-core;.-puppeteer-core-13.7.0 \
/node_modules/puppeteer-core/node_modules/rimraf;.-rimraf-3.0.2 \
/node_modules/puppeteer-core/node_modules/devtools-protocol;.-devtools-protocol-0.0.981744 \
/node_modules/punycode;.-punycode-2.3.1 \
/node_modules/pump;.-pump-3.0.0 \
/node_modules/ps-list;.-ps-list-7.2.0 \
/node_modules/proxy-from-env;.-proxy-from-env-1.1.0 \
/node_modules/prop-types;.-prop-types-15.8.1 \
/node_modules/promise-retry;.-promise-retry-2.0.1 \
/node_modules/progress;.-progress-2.0.3 \
/node_modules/process-nextick-args;.-process-nextick-args-2.0.1 \
/node_modules/pretty-format;.-pretty-format-29.7.0 \
/node_modules/pretty-format/node_modules/react-is;.-react-is-18.2.0 \
/node_modules/pretty-format/node_modules/ansi-styles;.-ansi-styles-5.2.0 \
/node_modules/prepend-http;.-prepend-http-2.0.0 \
/node_modules/prelude-ls;.-prelude-ls-1.2.1 \
/node_modules/postcss;.-postcss-8.4.33 \
/node_modules/plist;.-plist-3.1.0 \
/node_modules/pkg-up;.-pkg-up-3.1.0 \
/node_modules/pkg-types;.-pkg-types-1.0.3 \
/node_modules/pkg-dir;.-pkg-dir-4.2.0 \
/node_modules/pkg-dir/node_modules/path-exists;.-path-exists-4.0.0 \
/node_modules/pkg-dir/node_modules/p-locate;.-p-locate-4.1.0 \
/node_modules/pkg-dir/node_modules/locate-path;.-locate-path-5.0.0 \
/node_modules/pkg-dir/node_modules/find-up;.-find-up-4.1.0 \
/node_modules/pkg-conf;.-pkg-conf-3.1.0 \
/node_modules/pify;.-pify-4.0.1 \
/node_modules/picocolors;.-picocolors-1.0.0 \
/node_modules/pend;.-pend-1.2.0 \
/node_modules/pause-stream;.-pause-stream-0.0.11 \
/node_modules/pathval;.-pathval-1.1.1 \
/node_modules/pathe;.-pathe-1.1.2 \
/node_modules/path-scurry;.-path-scurry-1.10.1 \
/node_modules/path-scurry/node_modules/lru-cache;.-lru-cache-10.1.0 \
/node_modules/path-parse;.-path-parse-1.0.7 \
/node_modules/path-key;.-path-key-3.1.1 \
/node_modules/path-is-absolute;.-path-is-absolute-1.0.1 \
/node_modules/path-exists;.-path-exists-3.0.0 \
/node_modules/parse-json;.-parse-json-4.0.0 \
/node_modules/parent-module;.-parent-module-1.0.1 \
/node_modules/p-try;.-p-try-2.2.0 \
/node_modules/p-locate;.-p-locate-3.0.0 \
/node_modules/p-limit;.-p-limit-2.3.0 \
/node_modules/p-iteration;.-p-iteration-1.1.8 \
/node_modules/p-cancelable;.-p-cancelable-2.1.1 \
/node_modules/optionator;.-optionator-0.9.3 \
/node_modules/onetime;.-onetime-5.1.2 \
/node_modules/onetime/node_modules/mimic-fn;.-mimic-fn-2.1.0 \
/node_modules/once;.-once-1.4.0 \
/node_modules/object.values;.-object.values-1.1.7 \
/node_modules/object.hasown;.-object.hasown-1.1.3 \
/node_modules/object.groupby;.-object.groupby-1.0.1 \
/node_modules/object.fromentries;.-object.fromentries-2.0.7 \
/node_modules/object.entries;.-object.entries-1.1.7 \
/node_modules/object.assign;.-object.assign-4.1.5 \
/node_modules/object-keys;.-object-keys-1.1.1 \
/node_modules/object-inspect;.-object-inspect-1.13.1 \
/node_modules/object-assign;.-object-assign-4.1.1 \
/node_modules/npm-run-path;.-npm-run-path-5.2.0 \
/node_modules/npm-run-path/node_modules/path-key;.-path-key-4.0.0 \
/node_modules/normalize-url;.-normalize-url-6.1.0 \
/node_modules/normalize-path;.-normalize-path-3.0.0 \
/node_modules/node-releases;.-node-releases-2.0.14 \
/node_modules/node-fetch;.-node-fetch-2.6.7 \
/node_modules/node-addon-api;.-node-addon-api-1.7.2 \
/node_modules/natural-compare;.-natural-compare-1.4.0 \
/node_modules/nanoid;.-nanoid-3.3.7 \
/node_modules/ms;.-ms-2.1.2 \
/node_modules/mlly;.-mlly-1.5.0 \
/node_modules/mkdirp;.-mkdirp-1.0.4 \
/node_modules/mkdirp-classic;.-mkdirp-classic-0.5.3 \
/node_modules/minizlib;.-minizlib-2.1.2 \
/node_modules/minizlib/node_modules/minipass;.-minipass-3.3.6 \
/node_modules/minipass;.-minipass-5.0.0 \
/node_modules/minimist;.-minimist-1.2.8 \
/node_modules/minimatch;.-minimatch-5.1.6 \
/node_modules/mimic-response;.-mimic-response-1.0.1 \
/node_modules/mimic-fn;.-mimic-fn-3.1.0 \
/node_modules/mime;.-mime-2.6.0 \
/node_modules/mime-types;.-mime-types-2.1.35 \
/node_modules/mime-db;.-mime-db-1.52.0 \
/node_modules/merge-stream;.-merge-stream-2.0.0 \
/node_modules/meeussunmoon;.-meeussunmoon-3.0.3 \
/node_modules/meeussunmoon/node_modules/luxon;.-luxon-1.28.1 \
/node_modules/marky;.-marky-1.2.5 \
/node_modules/map-stream;.-map-stream-0.0.7 \
/node_modules/make-dir;.-make-dir-4.0.0 \
/node_modules/magicast;.-magicast-0.3.3 \
/node_modules/magic-string;.-magic-string-0.30.5 \
/node_modules/macos-notification-state;.-macos-notification-state-3.0.0 \
/node_modules/macos-notification-state/node_modules/node-addon-api;.-node-addon-api-3.0.0 \
/node_modules/luxon;.-luxon-3.4.4 \
/node_modules/lru-cache;.-lru-cache-6.0.0 \
/node_modules/lowercase-keys;.-lowercase-keys-2.0.0 \
/node_modules/loupe;.-loupe-2.3.7 \
/node_modules/loose-envify;.-loose-envify-1.4.0 \
/node_modules/long;.-long-5.2.1 \
/node_modules/loglevel;.-loglevel-1.8.1 \
/node_modules/loglevel-plugin-prefix;.-loglevel-plugin-prefix-0.8.4 \
/node_modules/lodash;.-lodash-4.17.21 \
/node_modules/lodash.zip;.-lodash.zip-4.2.0 \
/node_modules/lodash.union;.-lodash.union-4.6.0 \
/node_modules/lodash.merge;.-lodash.merge-4.6.2 \
/node_modules/lodash.isplainobject;.-lodash.isplainobject-4.0.6 \
/node_modules/lodash.isobject;.-lodash.isobject-3.0.2 \
/node_modules/lodash.flatten;.-lodash.flatten-4.4.0 \
/node_modules/lodash.difference;.-lodash.difference-4.5.0 \
/node_modules/lodash.defaults;.-lodash.defaults-4.2.0 \
/node_modules/lodash.clonedeep;.-lodash.clonedeep-4.5.0 \
/node_modules/locate-path;.-locate-path-3.0.0 \
/node_modules/local-pkg;.-local-pkg-0.5.0 \
/node_modules/load-json-file;.-load-json-file-5.3.0 \
/node_modules/load-json-file/node_modules/type-fest;.-type-fest-0.3.1 \
/node_modules/lighthouse-logger;.-lighthouse-logger-1.4.2 \
/node_modules/lighthouse-logger/node_modules/ms;.-ms-2.0.0 \
/node_modules/lighthouse-logger/node_modules/debug;.-debug-2.6.9 \
/node_modules/levn;.-levn-0.4.1 \
/node_modules/lazystream;.-lazystream-1.0.1 \
/node_modules/lazystream/node_modules/string_decoder;.-string_decoder-1.1.1 \
/node_modules/lazystream/node_modules/safe-buffer;.-safe-buffer-5.1.2 \
/node_modules/lazystream/node_modules/readable-stream;.-readable-stream-2.3.8 \
/node_modules/lazystream/node_modules/isarray;.-isarray-1.0.0 \
/node_modules/lazy-val;.-lazy-val-1.0.5 \
/node_modules/ky;.-ky-0.28.7 \
/node_modules/keyv;.-keyv-4.5.4 \
/node_modules/jsx-ast-utils;.-jsx-ast-utils-3.3.5 \
/node_modules/jsonfile;.-jsonfile-4.0.0 \
/node_modules/jsonc-parser;.-jsonc-parser-3.2.0 \
/node_modules/json5;.-json5-2.2.3 \
/node_modules/json-stable-stringify-without-jsonify;.-json-stable-stringify-without-jsonify-1.0.1 \
/node_modules/json-schema-typed;.-json-schema-typed-7.0.3 \
/node_modules/json-schema-traverse;.-json-schema-traverse-0.4.1 \
/node_modules/json-parse-better-errors;.-json-parse-better-errors-1.0.2 \
/node_modules/json-buffer;.-json-buffer-3.0.1 \
/node_modules/jsesc;.-jsesc-2.5.2 \
/node_modules/js-yaml;.-js-yaml-4.1.0 \
/node_modules/js-tokens;.-js-tokens-4.0.0 \
/node_modules/jake;.-jake-10.8.7 \
/node_modules/jake/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/jake/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/jackspeak;.-jackspeak-2.3.6 \
/node_modules/iterator.prototype;.-iterator.prototype-1.1.2 \
/node_modules/istanbul-reports;.-istanbul-reports-3.1.6 \
/node_modules/istanbul-lib-source-maps;.-istanbul-lib-source-maps-4.0.1 \
/node_modules/istanbul-lib-report;.-istanbul-lib-report-3.0.1 \
/node_modules/istanbul-lib-instrument;.-istanbul-lib-instrument-6.0.1 \
/node_modules/istanbul-lib-coverage;.-istanbul-lib-coverage-3.2.2 \
/node_modules/isexe;.-isexe-2.0.0 \
/node_modules/isbinaryfile;.-isbinaryfile-5.0.2 \
/node_modules/isarray;.-isarray-2.0.5 \
/node_modules/is-wsl;.-is-wsl-2.2.0 \
/node_modules/is-weakset;.-is-weakset-2.0.2 \
/node_modules/is-weakref;.-is-weakref-1.0.2 \
/node_modules/is-weakmap;.-is-weakmap-2.0.1 \
/node_modules/is-typed-array;.-is-typed-array-1.1.12 \
/node_modules/is-symbol;.-is-symbol-1.0.4 \
/node_modules/is-string;.-is-string-1.0.7 \
/node_modules/is-stream;.-is-stream-3.0.0 \
/node_modules/is-shared-array-buffer;.-is-shared-array-buffer-1.0.2 \
/node_modules/is-set;.-is-set-2.0.2 \
/node_modules/is-regex;.-is-regex-1.1.4 \
/node_modules/is-path-inside;.-is-path-inside-3.0.3 \
/node_modules/is-obj;.-is-obj-2.0.0 \
/node_modules/is-number-object;.-is-number-object-1.0.7 \
/node_modules/is-negative-zero;.-is-negative-zero-2.0.2 \
/node_modules/is-map;.-is-map-2.0.2 \
/node_modules/is-glob;.-is-glob-4.0.3 \
/node_modules/is-generator-function;.-is-generator-function-1.0.10 \
/node_modules/is-fullwidth-code-point;.-is-fullwidth-code-point-3.0.0 \
/node_modules/is-finalizationregistry;.-is-finalizationregistry-1.0.2 \
/node_modules/is-extglob;.-is-extglob-2.1.1 \
/node_modules/is-docker;.-is-docker-2.2.1 \
/node_modules/is-date-object;.-is-date-object-1.0.5 \
/node_modules/is-core-module;.-is-core-module-2.13.1 \
/node_modules/is-ci;.-is-ci-3.0.1 \
/node_modules/is-callable;.-is-callable-1.2.7 \
/node_modules/is-boolean-object;.-is-boolean-object-1.1.2 \
/node_modules/is-bigint;.-is-bigint-1.0.4 \
/node_modules/is-async-function;.-is-async-function-2.0.0 \
/node_modules/is-arrayish;.-is-arrayish-0.2.1 \
/node_modules/is-array-buffer;.-is-array-buffer-3.0.2 \
/node_modules/internal-slot;.-internal-slot-1.0.6 \
/node_modules/inherits;.-inherits-2.0.4 \
/node_modules/inflight;.-inflight-1.0.6 \
/node_modules/imurmurhash;.-imurmurhash-0.1.4 \
/node_modules/import-fresh;.-import-fresh-3.3.0 \
/node_modules/ignore;.-ignore-5.3.0 \
/node_modules/ieee754;.-ieee754-1.2.1 \
/node_modules/iconv-lite;.-iconv-lite-0.6.3 \
/node_modules/i18next;.-i18next-23.7.18 \
/node_modules/i18next-fs-backend;.-i18next-fs-backend-2.3.1 \
/node_modules/husky;.-husky-8.0.3 \
/node_modules/humanize-duration;.-humanize-duration-3.31.0 \
/node_modules/human-signals;.-human-signals-5.0.0 \
/node_modules/https-proxy-agent;.-https-proxy-agent-5.0.1 \
/node_modules/http2-wrapper;.-http2-wrapper-1.0.3 \
/node_modules/http-proxy-agent;.-http-proxy-agent-5.0.0 \
/node_modules/http-cache-semantics;.-http-cache-semantics-4.1.1 \
/node_modules/html-escaper;.-html-escaper-2.0.2 \
/node_modules/hosted-git-info;.-hosted-git-info-4.1.0 \
/node_modules/hasown;.-hasown-2.0.0 \
/node_modules/has-tostringtag;.-has-tostringtag-1.0.0 \
/node_modules/has-symbols;.-has-symbols-1.0.3 \
/node_modules/has-proto;.-has-proto-1.0.1 \
/node_modules/has-property-descriptors;.-has-property-descriptors-1.0.1 \
/node_modules/has-flag;.-has-flag-4.0.0 \
/node_modules/has-bigints;.-has-bigints-1.0.2 \
/node_modules/graphemer;.-graphemer-1.4.0 \
/node_modules/grapheme-splitter;.-grapheme-splitter-1.0.4 \
/node_modules/graceful-fs;.-graceful-fs-4.2.11 \
/node_modules/got;.-got-11.8.6 \
/node_modules/gopd;.-gopd-1.0.1 \
/node_modules/globalthis;.-globalthis-1.0.3 \
/node_modules/globals;.-globals-11.12.0 \
/node_modules/glob;.-glob-7.2.3 \
/node_modules/glob/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/glob/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/glob-parent;.-glob-parent-6.0.2 \
/node_modules/get-symbol-description;.-get-symbol-description-1.0.0 \
/node_modules/get-stream;.-get-stream-5.2.0 \
/node_modules/get-stdin;.-get-stdin-8.0.0 \
/node_modules/get-port;.-get-port-5.1.1 \
/node_modules/get-intrinsic;.-get-intrinsic-1.2.2 \
/node_modules/get-func-name;.-get-func-name-2.0.2 \
/node_modules/get-caller-file;.-get-caller-file-2.0.5 \
/node_modules/gensync;.-gensync-1.0.0-beta.2 \
/node_modules/functions-have-names;.-functions-have-names-1.2.3 \
/node_modules/function.prototype.name;.-function.prototype.name-1.1.6 \
/node_modules/function-bind;.-function-bind-1.1.2 \
/node_modules/fs.realpath;.-fs.realpath-1.0.0 \
/node_modules/fs-minipass;.-fs-minipass-2.1.0 \
/node_modules/fs-minipass/node_modules/minipass;.-minipass-3.3.6 \
/node_modules/fs-extra;.-fs-extra-8.1.0 \
/node_modules/fs-constants;.-fs-constants-1.0.0 \
/node_modules/from;.-from-0.1.7 \
/node_modules/form-data;.-form-data-4.0.0 \
/node_modules/foreground-child;.-foreground-child-3.1.1 \
/node_modules/for-each;.-for-each-0.3.3 \
/node_modules/flatted;.-flatted-3.2.9 \
/node_modules/flat-cache;.-flat-cache-3.2.0 \
/node_modules/flat-cache/node_modules/rimraf;.-rimraf-3.0.2 \
/node_modules/find-up;.-find-up-3.0.0 \
/node_modules/filelist;.-filelist-1.0.4 \
/node_modules/file-uri-to-path;.-file-uri-to-path-1.0.0 \
/node_modules/file-entry-cache;.-file-entry-cache-6.0.1 \
/node_modules/fd-slicer;.-fd-slicer-1.1.0 \
/node_modules/fastq;.-fastq-1.16.0 \
/node_modules/fast-levenshtein;.-fast-levenshtein-2.0.6 \
/node_modules/fast-json-stable-stringify;.-fast-json-stable-stringify-2.1.0 \
/node_modules/fast-deep-equal;.-fast-deep-equal-3.1.3 \
/node_modules/extract-zip;.-extract-zip-2.0.1 \
/node_modules/execa;.-execa-8.0.1 \
/node_modules/execa/node_modules/onetime;.-onetime-6.0.0 \
/node_modules/execa/node_modules/mimic-fn;.-mimic-fn-4.0.0 \
/node_modules/execa/node_modules/get-stream;.-get-stream-8.0.1 \
/node_modules/event-stream;.-event-stream-4.0.1 \
/node_modules/esutils;.-esutils-2.0.3 \
/node_modules/estree-walker;.-estree-walker-3.0.3 \
/node_modules/estraverse;.-estraverse-5.3.0 \
/node_modules/esrecurse;.-esrecurse-4.3.0 \
/node_modules/esquery;.-esquery-1.5.0 \
/node_modules/espree;.-espree-9.6.1 \
/node_modules/eslint;.-eslint-8.56.0 \
/node_modules/eslint/node_modules/yocto-queue;.-yocto-queue-0.1.0 \
/node_modules/eslint/node_modules/type-fest;.-type-fest-0.20.2 \
/node_modules/eslint/node_modules/path-exists;.-path-exists-4.0.0 \
/node_modules/eslint/node_modules/p-locate;.-p-locate-5.0.0 \
/node_modules/eslint/node_modules/p-limit;.-p-limit-3.1.0 \
/node_modules/eslint/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/eslint/node_modules/locate-path;.-locate-path-6.0.0 \
/node_modules/eslint/node_modules/globals;.-globals-13.24.0 \
/node_modules/eslint/node_modules/find-up;.-find-up-5.0.0 \
/node_modules/eslint/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/eslint-visitor-keys;.-eslint-visitor-keys-3.4.3 \
/node_modules/eslint-utils;.-eslint-utils-3.0.0 \
/node_modules/eslint-utils/node_modules/eslint-visitor-keys;.-eslint-visitor-keys-2.1.0 \
/node_modules/eslint-scope;.-eslint-scope-7.2.2 \
/node_modules/eslint-plugin-react;.-eslint-plugin-react-7.33.2 \
/node_modules/eslint-plugin-react/node_modules/semver;.-semver-6.3.1 \
/node_modules/eslint-plugin-react/node_modules/resolve;.-resolve-2.0.0-next.5 \
/node_modules/eslint-plugin-react/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/eslint-plugin-react/node_modules/doctrine;.-doctrine-2.1.0 \
/node_modules/eslint-plugin-react/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/eslint-plugin-promise;.-eslint-plugin-promise-6.1.1 \
/node_modules/eslint-plugin-n;.-eslint-plugin-n-15.7.0 \
/node_modules/eslint-plugin-n/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/eslint-plugin-n/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/eslint-plugin-import;.-eslint-plugin-import-2.29.1 \
/node_modules/eslint-plugin-import/node_modules/semver;.-semver-6.3.1 \
/node_modules/eslint-plugin-import/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/eslint-plugin-import/node_modules/doctrine;.-doctrine-2.1.0 \
/node_modules/eslint-plugin-import/node_modules/debug;.-debug-3.2.7 \
/node_modules/eslint-plugin-import/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/eslint-plugin-es;.-eslint-plugin-es-4.1.0 \
/node_modules/eslint-plugin-es/node_modules/eslint-visitor-keys;.-eslint-visitor-keys-1.3.0 \
/node_modules/eslint-plugin-es/node_modules/eslint-utils;.-eslint-utils-2.1.0 \
/node_modules/eslint-module-utils;.-eslint-module-utils-2.8.0 \
/node_modules/eslint-module-utils/node_modules/debug;.-debug-3.2.7 \
/node_modules/eslint-import-resolver-node;.-eslint-import-resolver-node-0.3.9 \
/node_modules/eslint-import-resolver-node/node_modules/debug;.-debug-3.2.7 \
/node_modules/eslint-config-standard;.-eslint-config-standard-17.1.0 \
/node_modules/eslint-config-standard-jsx;.-eslint-config-standard-jsx-11.0.0 \
/node_modules/escape-string-regexp;.-escape-string-regexp-4.0.0 \
/node_modules/escalade;.-escalade-3.1.1 \
/node_modules/esbuild;.-esbuild-0.19.11 \
/node_modules/es-to-primitive;.-es-to-primitive-1.2.1 \
/node_modules/es-shim-unscopables;.-es-shim-unscopables-1.0.2 \
/node_modules/es-set-tostringtag;.-es-set-tostringtag-2.0.2 \
/node_modules/es-iterator-helpers;.-es-iterator-helpers-1.0.15 \
/node_modules/es-abstract;.-es-abstract-1.22.3 \
/node_modules/error-ex;.-error-ex-1.3.2 \
/node_modules/err-code;.-err-code-2.0.3 \
/node_modules/env-paths;.-env-paths-2.2.1 \
/node_modules/end-of-stream;.-end-of-stream-1.4.4 \
/node_modules/emoji-regex;.-emoji-regex-8.0.0 \
/node_modules/electron;.-electron-28.1.4 \
/node_modules/electron-to-chromium;.-electron-to-chromium-1.4.640 \
/node_modules/electron-store;.-electron-store-8.1.0 \
/node_modules/electron-publish;.-electron-publish-24.13.1 \
/node_modules/electron-publish/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/electron-publish/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/electron-publish/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/electron-log;.-electron-log-5.0.3 \
/node_modules/electron-chromedriver;.-electron-chromedriver-17.0.0 \
/node_modules/electron-chromedriver/node_modules/semver;.-semver-6.3.1 \
/node_modules/electron-chromedriver/node_modules/responselike;.-responselike-1.0.2 \
/node_modules/electron-chromedriver/node_modules/responselike/node_modules/lowercase-keys;.-lowercase-keys-1.0.1 \
/node_modules/electron-chromedriver/node_modules/p-cancelable;.-p-cancelable-1.1.0 \
/node_modules/electron-chromedriver/node_modules/normalize-url;.-normalize-url-4.5.1 \
/node_modules/electron-chromedriver/node_modules/keyv;.-keyv-3.1.0 \
/node_modules/electron-chromedriver/node_modules/json-buffer;.-json-buffer-3.0.0 \
/node_modules/electron-chromedriver/node_modules/got;.-got-9.6.0 \
/node_modules/electron-chromedriver/node_modules/got/node_modules/lowercase-keys;.-lowercase-keys-1.0.1 \
/node_modules/electron-chromedriver/node_modules/got/node_modules/get-stream;.-get-stream-4.1.0 \
/node_modules/electron-chromedriver/node_modules/defer-to-connect;.-defer-to-connect-1.1.3 \
/node_modules/electron-chromedriver/node_modules/decompress-response;.-decompress-response-3.3.0 \
/node_modules/electron-chromedriver/node_modules/cacheable-request;.-cacheable-request-6.1.0 \
/node_modules/electron-chromedriver/node_modules/@szmarczak/http-timer;@szmarczak-http-timer-1.1.2 \
/node_modules/electron-chromedriver/node_modules/@sindresorhus/is;@sindresorhus-is-0.14.0 \
/node_modules/electron-chromedriver/node_modules/@electron/get;@electron-get-1.14.1 \
/node_modules/electron-builder;.-electron-builder-24.13.3 \
/node_modules/electron-builder/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/electron-builder/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/electron-builder/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/electron-builder-squirrel-windows;.-electron-builder-squirrel-windows-24.13.3 \
/node_modules/electron-builder-squirrel-windows/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/electron-builder-squirrel-windows/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/electron-builder-squirrel-windows/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/ejs;.-ejs-3.1.9 \
/node_modules/edge-paths;.-edge-paths-2.2.1 \
/node_modules/eastasianwidth;.-eastasianwidth-0.2.0 \
/node_modules/duplexer;.-duplexer-0.1.2 \
/node_modules/duplexer3;.-duplexer3-0.1.5 \
/node_modules/dotenv;.-dotenv-9.0.2 \
/node_modules/dotenv-expand;.-dotenv-expand-5.1.0 \
/node_modules/dot-prop;.-dot-prop-6.0.1 \
/node_modules/doctrine;.-doctrine-3.0.0 \
/node_modules/dmg-builder;.-dmg-builder-24.13.3 \
/node_modules/dmg-builder/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/dmg-builder/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/dmg-builder/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/dir-compare;.-dir-compare-3.3.0 \
/node_modules/dir-compare/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/dir-compare/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/diff-sequences;.-diff-sequences-29.6.3 \
/node_modules/devtools;.-devtools-7.16.13 \
/node_modules/devtools/node_modules/@types/node;@types-node-17.0.45 \
/node_modules/devtools-protocol;.-devtools-protocol-0.0.953906 \
/node_modules/dev-null;.-dev-null-0.1.1 \
/node_modules/dequal;.-dequal-2.0.3 \
/node_modules/delayed-stream;.-delayed-stream-1.0.0 \
/node_modules/define-properties;.-define-properties-1.2.1 \
/node_modules/define-data-property;.-define-data-property-1.1.1 \
/node_modules/defer-to-connect;.-defer-to-connect-2.0.1 \
/node_modules/deepmerge;.-deepmerge-4.3.1 \
/node_modules/deep-is;.-deep-is-0.1.4 \
/node_modules/deep-eql;.-deep-eql-4.1.3 \
/node_modules/decompress-response;.-decompress-response-6.0.0 \
/node_modules/decompress-response/node_modules/mimic-response;.-mimic-response-3.1.0 \
/node_modules/debug;.-debug-4.3.4 \
/node_modules/debounce-fn;.-debounce-fn-4.0.0 \
/node_modules/css-value;.-css-value-0.0.1 \
/node_modules/css-shorthand-properties;.-css-shorthand-properties-1.1.1 \
/node_modules/cross-spawn;.-cross-spawn-7.0.3 \
/node_modules/cross-fetch;.-cross-fetch-3.1.5 \
/node_modules/cross-env;.-cross-env-7.0.3 \
/node_modules/crc32-stream;.-crc32-stream-4.0.3 \
/node_modules/crc-32;.-crc-32-1.2.2 \
/node_modules/core-util-is;.-core-util-is-1.0.2 \
/node_modules/convert-source-map;.-convert-source-map-2.0.0 \
/node_modules/config-file-ts;.-config-file-ts-0.2.6 \
/node_modules/config-file-ts/node_modules/minimatch;.-minimatch-9.0.3 \
/node_modules/config-file-ts/node_modules/glob;.-glob-10.3.10 \
/node_modules/conf;.-conf-10.2.0 \
/node_modules/conf/node_modules/json-schema-traverse;.-json-schema-traverse-1.0.0 \
/node_modules/conf/node_modules/ajv;.-ajv-8.12.0 \
/node_modules/concat-map;.-concat-map-0.0.1 \
/node_modules/compress-commons;.-compress-commons-4.1.2 \
/node_modules/compare-version;.-compare-version-0.1.2 \
/node_modules/commander;.-commander-5.1.0 \
/node_modules/combined-stream;.-combined-stream-1.0.8 \
/node_modules/color-name;.-color-name-1.1.4 \
/node_modules/color-convert;.-color-convert-2.0.1 \
/node_modules/clone-response;.-clone-response-1.0.3 \
/node_modules/cliui;.-cliui-8.0.1 \
/node_modules/ci-info;.-ci-info-3.9.0 \
/node_modules/chromium-pickle-js;.-chromium-pickle-js-0.2.0 \
/node_modules/chrome-launcher;.-chrome-launcher-0.15.2 \
/node_modules/chownr;.-chownr-2.0.0 \
/node_modules/check-error;.-check-error-1.0.3 \
/node_modules/chalk;.-chalk-4.1.2 \
/node_modules/chai;.-chai-4.4.1 \
/node_modules/caniuse-lite;.-caniuse-lite-1.0.30001579 \
/node_modules/callsites;.-callsites-3.1.0 \
/node_modules/call-bind;.-call-bind-1.0.5 \
/node_modules/cacheable-request;.-cacheable-request-7.0.4 \
/node_modules/cacheable-lookup;.-cacheable-lookup-5.0.4 \
/node_modules/cac;.-cac-6.7.14 \
/node_modules/builtins;.-builtins-5.0.1 \
/node_modules/builder-util;.-builder-util-24.13.1 \
/node_modules/builder-util/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/builder-util/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/builder-util/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/builder-util-runtime;.-builder-util-runtime-9.2.4 \
/node_modules/buffer;.-buffer-5.7.1 \
/node_modules/buffer-from;.-buffer-from-1.1.2 \
/node_modules/buffer-equal;.-buffer-equal-1.0.1 \
/node_modules/buffer-crc32;.-buffer-crc32-0.2.13 \
/node_modules/browserslist;.-browserslist-4.22.2 \
/node_modules/brace-expansion;.-brace-expansion-2.0.1 \
/node_modules/bluebird;.-bluebird-3.7.2 \
/node_modules/bluebird-lst;.-bluebird-lst-1.0.9 \
/node_modules/bl;.-bl-4.1.0 \
/node_modules/bindings;.-bindings-1.5.0 \
/node_modules/base64-js;.-base64-js-1.5.1 \
/node_modules/balanced-match;.-balanced-match-1.0.2 \
/node_modules/available-typed-arrays;.-available-typed-arrays-1.0.5 \
/node_modules/atomically;.-atomically-1.7.0 \
/node_modules/at-least-node;.-at-least-node-1.0.0 \
/node_modules/asynckit;.-asynckit-0.4.0 \
/node_modules/asynciterator.prototype;.-asynciterator.prototype-1.0.0 \
/node_modules/async;.-async-3.2.5 \
/node_modules/async-exit-hook;.-async-exit-hook-2.0.1 \
/node_modules/assertion-error;.-assertion-error-1.1.0 \
/node_modules/arraybuffer.prototype.slice;.-arraybuffer.prototype.slice-1.0.2 \
/node_modules/array.prototype.tosorted;.-array.prototype.tosorted-1.1.2 \
/node_modules/array.prototype.flatmap;.-array.prototype.flatmap-1.3.2 \
/node_modules/array.prototype.flat;.-array.prototype.flat-1.3.2 \
/node_modules/array.prototype.findlastindex;.-array.prototype.findlastindex-1.2.3 \
/node_modules/array-includes;.-array-includes-3.1.7 \
/node_modules/array-buffer-byte-length;.-array-buffer-byte-length-1.0.0 \
/node_modules/aria-query;.-aria-query-5.3.0 \
/node_modules/argparse;.-argparse-2.0.1 \
/node_modules/archiver;.-archiver-5.3.2 \
/node_modules/archiver-utils;.-archiver-utils-2.1.0 \
/node_modules/archiver-utils/node_modules/string_decoder;.-string_decoder-1.1.1 \
/node_modules/archiver-utils/node_modules/safe-buffer;.-safe-buffer-5.1.2 \
/node_modules/archiver-utils/node_modules/readable-stream;.-readable-stream-2.3.8 \
/node_modules/archiver-utils/node_modules/isarray;.-isarray-1.0.0 \
/node_modules/app-builder-lib;.-app-builder-lib-24.13.3 \
/node_modules/app-builder-lib/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/app-builder-lib/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/app-builder-lib/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/app-builder-bin;.-app-builder-bin-4.0.0 \
/node_modules/ansi-styles;.-ansi-styles-4.3.0 \
/node_modules/ansi-regex;.-ansi-regex-5.0.1 \
/node_modules/ajv;.-ajv-6.12.6 \
/node_modules/ajv-keywords;.-ajv-keywords-3.5.2 \
/node_modules/ajv-formats;.-ajv-formats-2.1.1 \
/node_modules/ajv-formats/node_modules/json-schema-traverse;.-json-schema-traverse-1.0.0 \
/node_modules/ajv-formats/node_modules/ajv;.-ajv-8.12.0 \
/node_modules/agent-base;.-agent-base-6.0.2 \
/node_modules/acorn;.-acorn-8.11.3 \
/node_modules/acorn-walk;.-acorn-walk-8.3.2 \
/node_modules/acorn-jsx;.-acorn-jsx-5.3.2 \
/node_modules/@xmldom/xmldom;@xmldom-xmldom-0.8.10 \
/node_modules/@wdio/utils;@wdio-utils-7.16.13 \
/node_modules/@wdio/types;@wdio-types-7.16.13 \
/node_modules/@wdio/types/node_modules/@types/node;@types-node-17.0.45 \
/node_modules/@wdio/repl;@wdio-repl-7.16.13 \
/node_modules/@wdio/protocols;@wdio-protocols-7.16.7 \
/node_modules/@wdio/logger;@wdio-logger-7.16.0 \
/node_modules/@wdio/config;@wdio-config-7.16.13 \
/node_modules/@vitest/utils;@vitest-utils-1.2.1 \
/node_modules/@vitest/spy;@vitest-spy-1.2.1 \
/node_modules/@vitest/snapshot;@vitest-snapshot-1.2.1 \
/node_modules/@vitest/runner;@vitest-runner-1.2.1 \
/node_modules/@vitest/runner/node_modules/p-limit;.-p-limit-5.0.0 \
/node_modules/@vitest/expect;@vitest-expect-1.2.1 \
/node_modules/@vitest/coverage-istanbul;@vitest-coverage-istanbul-1.2.1 \
/node_modules/@ungap/structured-clone;@ungap-structured-clone-1.2.0 \
/node_modules/@types/which;@types-which-1.3.2 \
/node_modules/@types/ua-parser-js;@types-ua-parser-js-0.7.39 \
/node_modules/@types/responselike;@types-responselike-1.0.3 \
/node_modules/@types/node;@types-node-18.19.8 \
/node_modules/@types/ms;@types-ms-0.7.34 \
/node_modules/@types/keyv;@types-keyv-3.1.4 \
/node_modules/@types/json5;@types-json5-0.0.29 \
/node_modules/@types/http-cache-semantics;@types-http-cache-semantics-4.0.4 \
/node_modules/@types/fs-extra;@types-fs-extra-9.0.13 \
/node_modules/@types/estree;@types-estree-1.0.5 \
/node_modules/@types/debug;@types-debug-4.1.12 \
/node_modules/@types/cacheable-request;@types-cacheable-request-6.0.3 \
/node_modules/@types/aria-query;@types-aria-query-5.0.4 \
/node_modules/@tootallnate/once;@tootallnate-once-2.0.0 \
/node_modules/@szmarczak/http-timer;@szmarczak-http-timer-4.0.6 \
/node_modules/@sindresorhus/is;@sindresorhus-is-4.6.0 \
/node_modules/@sinclair/typebox;@sinclair-typebox-0.27.8 \
/node_modules/@nornagon/put;@nornagon-put-0.0.8 \
/node_modules/@nodelib/fs.walk;@nodelib-fs.walk-1.2.8 \
/node_modules/@nodelib/fs.stat;@nodelib-fs.stat-2.0.5 \
/node_modules/@nodelib/fs.scandir;@nodelib-fs.scandir-2.1.5 \
/node_modules/@malept/flatpak-bundler;@malept-flatpak-bundler-0.4.0 \
/node_modules/@malept/flatpak-bundler/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/@malept/flatpak-bundler/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/@malept/flatpak-bundler/node_modules/fs-extra;.-fs-extra-9.1.0 \
/node_modules/@malept/cross-spawn-promise;@malept-cross-spawn-promise-1.1.1 \
/node_modules/@jridgewell/trace-mapping;@jridgewell-trace-mapping-0.3.22 \
/node_modules/@jridgewell/sourcemap-codec;@jridgewell-sourcemap-codec-1.4.15 \
/node_modules/@jridgewell/set-array;@jridgewell-set-array-1.1.2 \
/node_modules/@jridgewell/resolve-uri;@jridgewell-resolve-uri-3.1.1 \
/node_modules/@jridgewell/gen-mapping;@jridgewell-gen-mapping-0.3.3 \
/node_modules/@jest/schemas;@jest-schemas-29.6.3 \
/node_modules/@istanbuljs/schema;@istanbuljs-schema-0.1.3 \
/node_modules/@isaacs/cliui;@isaacs-cliui-8.0.2 \
/node_modules/@isaacs/cliui/node_modules/wrap-ansi;.-wrap-ansi-8.1.0 \
/node_modules/@isaacs/cliui/node_modules/strip-ansi;.-strip-ansi-7.1.0 \
/node_modules/@isaacs/cliui/node_modules/string-width;.-string-width-5.1.2 \
/node_modules/@isaacs/cliui/node_modules/emoji-regex;.-emoji-regex-9.2.2 \
/node_modules/@isaacs/cliui/node_modules/ansi-styles;.-ansi-styles-6.2.1 \
/node_modules/@isaacs/cliui/node_modules/ansi-regex;.-ansi-regex-6.0.1 \
/node_modules/@humanwhocodes/object-schema;@humanwhocodes-object-schema-2.0.2 \
/node_modules/@humanwhocodes/module-importer;@humanwhocodes-module-importer-1.0.1 \
/node_modules/@humanwhocodes/config-array;@humanwhocodes-config-array-0.11.14 \
/node_modules/@humanwhocodes/config-array/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/@humanwhocodes/config-array/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/@eslint/js;@eslint-js-8.56.0 \
/node_modules/@eslint/eslintrc;@eslint-eslintrc-2.1.4 \
/node_modules/@eslint/eslintrc/node_modules/type-fest;.-type-fest-0.20.2 \
/node_modules/@eslint/eslintrc/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/@eslint/eslintrc/node_modules/globals;.-globals-13.24.0 \
/node_modules/@eslint/eslintrc/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/@eslint-community/regexpp;@eslint-community-regexpp-4.10.0 \
/node_modules/@eslint-community/eslint-utils;@eslint-community-eslint-utils-4.4.0 \
/node_modules/@electron/universal;@electron-universal-1.5.1 \
/node_modules/@electron/universal/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/@electron/universal/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/@electron/universal/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/@electron/universal/node_modules/fs-extra;.-fs-extra-9.1.0 \
/node_modules/@electron/universal/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/@electron/remote;@electron-remote-2.1.1 \
/node_modules/@electron/osx-sign;@electron-osx-sign-1.0.5 \
/node_modules/@electron/osx-sign/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/@electron/osx-sign/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/@electron/osx-sign/node_modules/isbinaryfile;.-isbinaryfile-4.0.10 \
/node_modules/@electron/osx-sign/node_modules/fs-extra;.-fs-extra-10.1.0 \
/node_modules/@electron/notarize;@electron-notarize-2.2.1 \
/node_modules/@electron/notarize/node_modules/universalify;.-universalify-2.0.1 \
/node_modules/@electron/notarize/node_modules/jsonfile;.-jsonfile-6.1.0 \
/node_modules/@electron/notarize/node_modules/fs-extra;.-fs-extra-9.1.0 \
/node_modules/@electron/get;@electron-get-2.0.3 \
/node_modules/@electron/get/node_modules/semver;.-semver-6.3.1 \
/node_modules/@electron/asar;@electron-asar-3.2.8 \
/node_modules/@electron/asar/node_modules/minimatch;.-minimatch-3.1.2 \
/node_modules/@electron/asar/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/node_modules/@develar/schema-utils;@develar-schema-utils-2.6.5 \
/node_modules/@babel/types;@babel-types-7.23.6 \
/node_modules/@babel/traverse;@babel-traverse-7.23.7 \
/node_modules/@babel/template;@babel-template-7.22.15 \
/node_modules/@babel/runtime;@babel-runtime-7.23.8 \
/node_modules/@babel/parser;@babel-parser-7.23.6 \
/node_modules/@babel/highlight;@babel-highlight-7.23.4 \
/node_modules/@babel/highlight/node_modules/supports-color;.-supports-color-5.5.0 \
/node_modules/@babel/highlight/node_modules/has-flag;.-has-flag-3.0.0 \
/node_modules/@babel/highlight/node_modules/escape-string-regexp;.-escape-string-regexp-1.0.5 \
/node_modules/@babel/highlight/node_modules/color-name;.-color-name-1.1.3 \
/node_modules/@babel/highlight/node_modules/color-convert;.-color-convert-1.9.3 \
/node_modules/@babel/highlight/node_modules/chalk;.-chalk-2.4.2 \
/node_modules/@babel/highlight/node_modules/ansi-styles;.-ansi-styles-3.2.1 \
/node_modules/@babel/helpers;@babel-helpers-7.23.8 \
/node_modules/@babel/helper-validator-option;@babel-helper-validator-option-7.23.5 \
/node_modules/@babel/helper-validator-identifier;@babel-helper-validator-identifier-7.22.20 \
/node_modules/@babel/helper-string-parser;@babel-helper-string-parser-7.23.4 \
/node_modules/@babel/helper-split-export-declaration;@babel-helper-split-export-declaration-7.22.6 \
/node_modules/@babel/helper-simple-access;@babel-helper-simple-access-7.22.5 \
/node_modules/@babel/helper-module-transforms;@babel-helper-module-transforms-7.23.3 \
/node_modules/@babel/helper-module-imports;@babel-helper-module-imports-7.22.15 \
/node_modules/@babel/helper-hoist-variables;@babel-helper-hoist-variables-7.22.5 \
/node_modules/@babel/helper-function-name;@babel-helper-function-name-7.23.0 \
/node_modules/@babel/helper-environment-visitor;@babel-helper-environment-visitor-7.22.20 \
/node_modules/@babel/helper-compilation-targets;@babel-helper-compilation-targets-7.23.6 \
/node_modules/@babel/helper-compilation-targets/node_modules/yallist;.-yallist-3.1.1 \
/node_modules/@babel/helper-compilation-targets/node_modules/semver;.-semver-6.3.1 \
/node_modules/@babel/helper-compilation-targets/node_modules/lru-cache;.-lru-cache-5.1.1 \
/node_modules/@babel/generator;@babel-generator-7.23.6 \
/node_modules/@babel/core;@babel-core-7.23.7 \
/node_modules/@babel/core/node_modules/semver;.-semver-6.3.1 \
/node_modules/@babel/compat-data;@babel-compat-data-7.23.5 \
/node_modules/@babel/code-frame;@babel-code-frame-7.23.5 \
/node_modules/@babel/code-frame/node_modules/supports-color;.-supports-color-5.5.0 \
/node_modules/@babel/code-frame/node_modules/has-flag;.-has-flag-3.0.0 \
/node_modules/@babel/code-frame/node_modules/escape-string-regexp;.-escape-string-regexp-1.0.5 \
/node_modules/@babel/code-frame/node_modules/color-name;.-color-name-1.1.3 \
/node_modules/@babel/code-frame/node_modules/color-convert;.-color-convert-1.9.3 \
/node_modules/@babel/code-frame/node_modules/chalk;.-chalk-2.4.2 \
/node_modules/@babel/code-frame/node_modules/ansi-styles;.-ansi-styles-3.2.1 \
/node_modules/@ampproject/remapping;@ampproject-remapping-2.2.1 \
/node_modules/@aashutoshrathi/word-wrap;@aashutoshrathi-word-wrap-1.2.6 \
/node_modules/7zip-bin;.-7zip-bin-5.2.0 \

