#!/bin/sh

# Kerberos support
if [ -n "$LD_LIBRARY_PATH" ]; then
	LD_LIBRARY_PATH="${TRUEPREFIX}/heimdal/lib:$LD_LIBRARY_PATH"
else
	LD_LIBRARY_PATH="${TRUEPREFIX}/heimdal/lib"
fi
export LD_LIBRARY_PATH

# XXX also --ms-enable-electron-run-as-node ?
ELECTRON_APP_NAME="${MODELECTRON_APP_NAME}" \
ELECTRON_UNVEIL="${MODELECTRON_UNVEIL_FILE}" \
ELECTRON_RUN_AS_NODE=1 \
exec ${TRUEPREFIX}/${ELECTRON_WRAPPER} \
	"${TRUEPREFIX}/${MODELECTRON_DIST_T}/out/cli.js" \
	--app="${TRUEPREFIX}/${MODELECTRON_DIST_T}" \
	--no-sandbox "${@}"
