# make modnpm-gen-modules > modules.inc
# MODNPM_OMITDEV=No 
# MODNPM_OMITOPTIONAL=Yes
# MODNPM_INCLUDES=
# MODNPM_EXCLUDES=
DIST_TUPLE += \
npm . 7zip-bin 5.1.1 . \
npm . 7zip-bin 5.2.0 . \
npm . 7zip-min 1.4.4 . \
npm . acorn 8.11.3 . \
npm . acorn-jsx 5.3.2 . \
npm . agent-base 6.0.2 . \
npm . ajv 6.12.6 . \
npm . ajv-keywords 3.5.2 . \
npm . ansi-regex 5.0.1 . \
npm . ansi-regex 6.0.1 . \
npm . ansi-styles 4.3.0 . \
npm . ansi-styles 6.2.1 . \
npm . any-base 1.1.0 . \
npm . anymatch 3.1.3 . \
npm . app-builder-bin 4.0.0 . \
npm . app-builder-lib 24.12.0 . \
npm . argparse 2.0.1 . \
npm . async 3.2.5 . \
npm . async-exit-hook 2.0.1 . \
npm . asynckit 0.4.0 . \
npm . at-least-node 1.0.0 . \
npm . balanced-match 1.0.2 . \
npm . base64-js 1.5.1 . \
npm . binary-extensions 2.2.0 . \
npm . bluebird 3.7.2 . \
npm . bluebird-lst 1.0.9 . \
npm . bmp-js 0.1.0 . \
npm . brace-expansion 1.1.11 . \
npm . brace-expansion 2.0.1 . \
npm . braces 3.0.2 . \
npm . buffer 5.7.1 . \
npm . buffer-crc32 0.2.13 . \
npm . buffer-equal 0.0.1 . \
npm . buffer-equal 1.0.1 . \
npm . buffer-from 1.1.2 . \
npm . builder-util 24.9.4 . \
npm . builder-util-runtime 9.2.3 . \
npm . cacheable-lookup 5.0.4 . \
npm . cacheable-request 7.0.4 . \
npm . call-bind 1.0.7 . \
npm . callsites 3.1.0 . \
npm . chalk 4.1.2 . \
npm . chokidar 3.6.0 . \
npm . chownr 2.0.0 . \
npm . chromium-pickle-js 0.2.0 . \
npm . ci-info 3.9.0 . \
npm . cliui 8.0.1 . \
npm . clone-response 1.0.3 . \
npm . color-convert 2.0.1 . \
npm . color-name 1.1.4 . \
npm . combined-stream 1.0.8 . \
npm . commander 5.1.0 . \
npm . compare-version 0.1.2 . \
npm . concat-map 0.0.1 . \
npm . config-file-ts 0.2.6 . \
npm . cross-spawn 7.0.3 . \
npm . debug 2.6.9 . \
npm . debug 4.3.4 . \
npm . decode-dxt 1.0.1 . \
npm . decompress-response 6.0.0 . \
npm . deep-is 0.1.4 . \
npm . defer-to-connect 2.0.1 . \
npm . define-data-property 1.1.4 . \
npm . delayed-stream 1.0.0 . \
npm . dir-compare 3.3.0 . \
npm . discord-rpc 4.0.1 . \
npm . dmg-builder 24.12.0 . \
npm . doctrine 3.0.0 . \
npm . dom-walk 0.1.2 . \
npm . dotenv 9.0.2 . \
npm . dotenv-expand 5.1.0 . \
npm . eastasianwidth 0.2.0 . \
npm . ejs 3.1.9 . \
npm . electron 29.1.0 . \
npm . electron-builder 24.12.0 . \
npm . electron-log 5.1.1 . \
npm . electron-publish 24.9.4 . \
npm . electron-settings 4.0.2 . \
npm . electron-updater 6.1.8 . \
npm . emoji-regex 8.0.0 . \
npm . emoji-regex 9.2.2 . \
npm . end-of-stream 1.4.4 . \
npm . env-paths 2.2.1 . \
npm . err-code 2.0.3 . \
npm . es-define-property 1.0.0 . \
npm . es-errors 1.3.0 . \
npm . escalade 3.1.2 . \
npm . escape-string-regexp 4.0.0 . \
npm . eslint 8.57.0 . \
npm . eslint-scope 7.2.2 . \
npm . eslint-visitor-keys 3.4.3 . \
npm . espree 9.6.1 . \
npm . esquery 1.5.0 . \
npm . esrecurse 4.3.0 . \
npm . estraverse 5.3.0 . \
npm . esutils 2.0.3 . \
npm . exif-parser 0.1.12 . \
npm . extract-zip 2.0.1 . \
npm . fast-deep-equal 3.1.3 . \
npm . fast-json-stable-stringify 2.1.0 . \
npm . fast-levenshtein 2.0.6 . \
npm . fastq 1.17.1 . \
npm . fd-slicer 1.1.0 . \
npm . file-entry-cache 6.0.1 . \
npm . file-type 16.5.4 . \
npm . filelist 1.0.4 . \
npm . fill-range 7.0.1 . \
npm . find-up 5.0.0 . \
npm . flat-cache 3.2.0 . \
npm . flatted 3.3.1 . \
npm . foreground-child 3.1.1 . \
npm . form-data 4.0.0 . \
npm . fs-extra 10.1.0 . \
npm . fs-extra 8.1.0 . \
npm . fs-extra 9.1.0 . \
npm . fs-minipass 2.1.0 . \
npm . fs.realpath 1.0.0 . \
npm . function-bind 1.1.2 . \
npm . get-caller-file 2.0.5 . \
npm . get-intrinsic 1.2.4 . \
npm . get-stream 5.2.0 . \
npm . gifwrap 0.10.1 . \
npm . glob 10.3.10 . \
npm . glob 7.2.3 . \
npm . glob-parent 5.1.2 . \
npm . glob-parent 6.0.2 . \
npm . global 4.4.0 . \
npm . globals 13.24.0 . \
npm . gopd 1.0.1 . \
npm . got 11.8.6 . \
npm . graceful-fs 4.2.11 . \
npm . graphemer 1.4.0 . \
npm . has-flag 4.0.0 . \
npm . has-property-descriptors 1.0.2 . \
npm . has-proto 1.0.3 . \
npm . has-symbols 1.0.3 . \
npm . hasown 2.0.1 . \
npm . hosted-git-info 4.1.0 . \
npm . http-cache-semantics 4.1.1 . \
npm . http-proxy-agent 5.0.0 . \
npm . http2-wrapper 1.0.3 . \
npm . https-proxy-agent 5.0.1 . \
npm . iconv-lite 0.6.3 . \
npm . ieee754 1.2.1 . \
npm . ignore 5.3.1 . \
npm . image-q 4.0.0 . \
npm . import-fresh 3.3.0 . \
npm . imurmurhash 0.1.4 . \
npm . inflight 1.0.6 . \
npm . inherits 2.0.4 . \
npm . is-binary-path 2.1.0 . \
npm . is-ci 3.0.1 . \
npm . is-extglob 2.1.1 . \
npm . is-fullwidth-code-point 3.0.0 . \
npm . is-function 1.0.2 . \
npm . is-glob 4.0.3 . \
npm . is-number 7.0.0 . \
npm . is-path-inside 3.0.3 . \
npm . is-typedarray 1.0.0 . \
npm . isarray 2.0.5 . \
npm . isbinaryfile 4.0.10 . \
npm . isbinaryfile 5.0.2 . \
npm . isexe 2.0.0 . \
npm . isomorphic-fetch 3.0.0 . \
npm . jackspeak 2.3.6 . \
npm . jake 10.8.7 . \
npm . jaz-ts-utils 6.3.2 . \
npm . jimp 0.22.12 . \
npm . jpeg-js 0.4.4 . \
npm . js-yaml 4.1.0 . \
npm . json-buffer 3.0.1 . \
npm . json-schema-traverse 0.4.1 . \
npm . json-stable-stringify 1.1.1 . \
npm . json-stable-stringify-without-jsonify 1.0.1 . \
npm . json5 2.2.3 . \
npm . jsonfile 4.0.0 . \
npm . jsonfile 6.1.0 . \
npm . jsonify 0.0.1 . \
npm . keyv 4.5.4 . \
npm . kysely 0.25.0 . \
npm . lazy-val 1.0.5 . \
npm . levn 0.4.1 . \
npm . load-bmfont 1.4.1 . \
npm . locate-path 6.0.0 . \
npm . lodash 4.17.21 . \
npm . lodash.defaultsdeep 4.6.1 . \
npm . lodash.defaultto 4.14.0 . \
npm . lodash.escaperegexp 4.1.2 . \
npm . lodash.flattendeep 4.4.0 . \
npm . lodash.get 4.4.2 . \
npm . lodash.has 4.5.2 . \
npm . lodash.isempty 4.4.0 . \
npm . lodash.isequal 4.5.0 . \
npm . lodash.merge 4.6.2 . \
npm . lodash.negate 3.0.2 . \
npm . lodash.set 4.3.2 . \
npm . lodash.unset 4.5.2 . \
npm . lowercase-keys 2.0.0 . \
npm . lru-cache 10.2.0 . \
npm . lru-cache 6.0.0 . \
npm . luaparse 0.3.1 . \
npm . mime 1.6.0 . \
npm . mime 2.6.0 . \
npm . mime-db 1.52.0 . \
npm . mime-types 2.1.35 . \
npm . mimic-response 1.0.1 . \
npm . mimic-response 3.1.0 . \
npm . min-document 2.19.0 . \
npm . minimatch 3.1.2 . \
npm . minimatch 5.1.6 . \
npm . minimatch 9.0.3 . \
npm . minimist 1.2.8 . \
npm . minipass 3.3.6 . \
npm . minipass 5.0.0 . \
npm . minizlib 2.1.2 . \
npm . mkdirp 1.0.4 . \
npm . ms 2.0.0 . \
npm . ms 2.1.2 . \
npm . natural-compare 1.4.0 . \
npm . node-7z 3.0.0 . \
npm . node-downloader-helper 2.1.9 . \
npm . node-fetch 2.7.0 . \
npm . node-gzip 1.1.2 . \
npm . node-stream-zip 1.15.0 . \
npm . normalize-path 3.0.0 . \
npm . normalize-url 6.1.0 . \
npm . object-keys 1.1.1 . \
npm . omggif 1.0.10 . \
npm . once 1.4.0 . \
npm . optionator 0.9.3 . \
npm . p-cancelable 2.1.1 . \
npm . p-limit 3.1.0 . \
npm . p-locate 5.0.0 . \
npm . pako 1.0.11 . \
npm . parent-module 1.0.1 . \
npm . parse-bmfont-ascii 1.0.6 . \
npm . parse-bmfont-binary 1.0.6 . \
npm . parse-bmfont-xml 1.1.6 . \
npm . parse-dds 1.2.1 . \
npm . parse-headers 2.0.5 . \
npm . path-exists 4.0.0 . \
npm . path-is-absolute 1.0.1 . \
npm . path-key 3.1.1 . \
npm . path-scurry 1.10.1 . \
npm . peek-readable 4.1.0 . \
npm . pend 1.2.0 . \
npm . phin 2.9.3 . \
npm . picomatch 2.3.1 . \
npm . pixelmatch 4.0.2 . \
npm . plist 3.1.0 . \
npm . pngjs 3.4.0 . \
npm . pngjs 6.0.0 . \
npm . prelude-ls 1.2.1 . \
npm . process 0.11.10 . \
npm . progress 2.0.3 . \
npm . promise-retry 2.0.1 . \
npm . pump 3.0.0 . \
npm . punycode 2.3.1 . \
npm . queue-microtask 1.2.3 . \
npm . quick-lru 5.1.1 . \
npm . read-config-file 6.3.2 . \
npm . readable-stream 3.6.2 . \
npm . readable-web-to-node-stream 3.0.2 . \
npm . readdirp 3.6.0 . \
npm . regenerator-runtime 0.13.11 . \
npm . require-directory 2.1.1 . \
npm . resolve-alpn 1.2.1 . \
npm . resolve-from 4.0.0 . \
npm . responselike 2.0.1 . \
npm . restructure 2.0.1 . \
npm . retry 0.12.0 . \
npm . reusify 1.0.4 . \
npm . rimraf 3.0.2 . \
npm . run-parallel 1.2.0 . \
npm . safe-buffer 5.2.1 . \
npm . safer-buffer 2.1.2 . \
npm . sanitize-filename 1.6.3 . \
npm . sax 1.3.0 . \
npm . sdfz-demo-parser 5.11.0 . \
npm . semver 6.3.1 . \
npm . semver 7.6.0 . \
npm . set-function-length 1.2.1 . \
npm . shebang-command 2.0.0 . \
npm . shebang-regex 3.0.0 . \
npm . signal-exit 3.0.7 . \
npm . signal-exit 4.1.0 . \
npm . simple-update-notifier 2.0.0 . \
npm . source-map 0.6.1 . \
npm . source-map-support 0.5.21 . \
npm . spring-map-parser 6.1.1 . \
npm . stat-mode 1.0.0 . \
npm . string-width 4.2.3 . \
npm . string-width 5.1.2 . \
npm . string_decoder 1.3.0 . \
npm . strip-ansi 6.0.1 . \
npm . strip-ansi 7.1.0 . \
npm . strip-json-comments 3.1.1 . \
npm . strtok3 6.3.0 . \
npm . sumchecker 3.0.1 . \
npm . supports-color 7.2.0 . \
npm . tar 6.2.0 . \
npm . temp-file 3.4.0 . \
npm . text-table 0.2.0 . \
npm . tga 1.0.7 . \
npm . timm 1.7.1 . \
npm . tiny-typed-emitter 2.1.0 . \
npm . tinycolor2 1.6.0 . \
npm . tmp 0.2.3 . \
npm . tmp-promise 3.0.3 . \
npm . to-regex-range 5.0.1 . \
npm . token-types 4.2.1 . \
npm . tr46 0.0.3 . \
npm . truncate-utf8-bytes 1.0.2 . \
npm . type-check 0.4.0 . \
npm . type-fest 0.20.2 . \
npm . typedarray-to-buffer 3.1.5 . \
npm . typescript 5.3.3 . \
npm . undici-types 5.26.5 . \
npm . universalify 0.1.2 . \
npm . universalify 2.0.1 . \
npm . uri-js 4.4.1 . \
npm . utf8-byte-length 1.0.4 . \
npm . utif2 4.1.0 . \
npm . util-deprecate 1.0.2 . \
npm . webidl-conversions 3.0.1 . \
npm . whatwg-fetch 3.6.20 . \
npm . whatwg-url 5.0.0 . \
npm . which 2.0.2 . \
npm . wrap-ansi 7.0.0 . \
npm . wrap-ansi 8.1.0 . \
npm . wrappy 1.0.2 . \
npm . write-file-atomic 3.0.3 . \
npm . ws 7.5.9 . \
npm . xhr 2.6.0 . \
npm . xml-parse-from-string 1.0.1 . \
npm . xml2js 0.5.0 . \
npm . xmlbuilder 11.0.1 . \
npm . xmlbuilder 15.1.1 . \
npm . xtend 4.0.2 . \
npm . y18n 5.0.8 . \
npm . yallist 4.0.0 . \
npm . yargs 17.7.2 . \
npm . yargs-parser 21.1.1 . \
npm . yauzl 2.10.0 . \
npm . yocto-queue 0.1.0 . \
npm @aashutoshrathi word-wrap 1.2.6 . \
npm @develar schema-utils 2.6.5 . \
npm @electron asar 3.2.8 . \
npm @electron get 2.0.3 . \
npm @electron notarize 2.1.0 . \
npm @electron osx-sign 1.0.5 . \
npm @electron remote 2.1.2 . \
npm @electron universal 1.4.1 . \
npm @eslint eslintrc 2.1.4 . \
npm @eslint js 8.57.0 . \
npm @eslint-community eslint-utils 4.4.0 . \
npm @eslint-community regexpp 4.10.0 . \
npm @humanwhocodes config-array 0.11.14 . \
npm @humanwhocodes module-importer 1.0.1 . \
npm @humanwhocodes object-schema 2.0.2 . \
npm @isaacs cliui 8.0.2 . \
npm @jimp bmp 0.22.12 . \
npm @jimp core 0.22.12 . \
npm @jimp custom 0.22.12 . \
npm @jimp gif 0.22.12 . \
npm @jimp jpeg 0.22.12 . \
npm @jimp plugin-blit 0.22.12 . \
npm @jimp plugin-blur 0.22.12 . \
npm @jimp plugin-circle 0.22.12 . \
npm @jimp plugin-color 0.22.12 . \
npm @jimp plugin-contain 0.22.12 . \
npm @jimp plugin-cover 0.22.12 . \
npm @jimp plugin-crop 0.22.12 . \
npm @jimp plugin-displace 0.22.12 . \
npm @jimp plugin-dither 0.22.12 . \
npm @jimp plugin-fisheye 0.22.12 . \
npm @jimp plugin-flip 0.22.12 . \
npm @jimp plugin-gaussian 0.22.12 . \
npm @jimp plugin-invert 0.22.12 . \
npm @jimp plugin-mask 0.22.12 . \
npm @jimp plugin-normalize 0.22.12 . \
npm @jimp plugin-print 0.22.12 . \
npm @jimp plugin-resize 0.22.12 . \
npm @jimp plugin-rotate 0.22.12 . \
npm @jimp plugin-scale 0.22.12 . \
npm @jimp plugin-shadow 0.22.12 . \
npm @jimp plugin-threshold 0.22.12 . \
npm @jimp plugins 0.22.12 . \
npm @jimp png 0.22.12 . \
npm @jimp tiff 0.22.12 . \
npm @jimp types 0.22.12 . \
npm @jimp utils 0.22.12 . \
npm @malept cross-spawn-promise 1.1.1 . \
npm @malept flatpak-bundler 0.4.0 . \
npm @nodelib fs.scandir 2.1.5 . \
npm @nodelib fs.stat 2.0.5 . \
npm @nodelib fs.walk 1.2.8 . \
npm @sindresorhus is 4.6.0 . \
npm @szmarczak http-timer 4.0.6 . \
npm @tokenizer token 0.3.0 . \
npm @tootallnate once 2.0.0 . \
npm @types cacheable-request 6.0.3 . \
npm @types debug 4.1.12 . \
npm @types fs-extra 9.0.13 . \
npm @types http-cache-semantics 4.0.4 . \
npm @types keyv 3.1.4 . \
npm @types ms 0.7.34 . \
npm @types node 16.9.1 . \
npm @types node 20.11.24 . \
npm @types responselike 1.0.3 . \
npm @ungap structured-clone 1.2.0 . \
npm @xmldom xmldom 0.8.10 . \

MODNPM_CP += \
/launcher/node_modules/yocto-queue;.-yocto-queue-0.1.0 \
/launcher/node_modules/yauzl;.-yauzl-2.10.0 \
/launcher/node_modules/yargs;.-yargs-17.7.2 \
/launcher/node_modules/yargs-parser;.-yargs-parser-21.1.1 \
/launcher/node_modules/yallist;.-yallist-4.0.0 \
/launcher/node_modules/y18n;.-y18n-5.0.8 \
/launcher/node_modules/xtend;.-xtend-4.0.2 \
/launcher/node_modules/xmlbuilder;.-xmlbuilder-15.1.1 \
/launcher/node_modules/xml2js;.-xml2js-0.5.0 \
/launcher/node_modules/xml2js/node_modules/xmlbuilder;.-xmlbuilder-11.0.1 \
/launcher/node_modules/xml-parse-from-string;.-xml-parse-from-string-1.0.1 \
/launcher/node_modules/xhr;.-xhr-2.6.0 \
/launcher/node_modules/ws;.-ws-7.5.9 \
/launcher/node_modules/write-file-atomic;.-write-file-atomic-3.0.3 \
/launcher/node_modules/wrappy;.-wrappy-1.0.2 \
/launcher/node_modules/wrap-ansi;.-wrap-ansi-7.0.0 \
/launcher/node_modules/wrap-ansi-cjs;.-wrap-ansi-7.0.0 \
/launcher/node_modules/which;.-which-2.0.2 \
/launcher/node_modules/whatwg-url;.-whatwg-url-5.0.0 \
/launcher/node_modules/whatwg-fetch;.-whatwg-fetch-3.6.20 \
/launcher/node_modules/webidl-conversions;.-webidl-conversions-3.0.1 \
/launcher/node_modules/util-deprecate;.-util-deprecate-1.0.2 \
/launcher/node_modules/utif2;.-utif2-4.1.0 \
/launcher/node_modules/utf8-byte-length;.-utf8-byte-length-1.0.4 \
/launcher/node_modules/uri-js;.-uri-js-4.4.1 \
/launcher/node_modules/universalify;.-universalify-0.1.2 \
/launcher/node_modules/undici-types;.-undici-types-5.26.5 \
/launcher/node_modules/typescript;.-typescript-5.3.3 \
/launcher/node_modules/typedarray-to-buffer;.-typedarray-to-buffer-3.1.5 \
/launcher/node_modules/type-fest;.-type-fest-0.20.2 \
/launcher/node_modules/type-check;.-type-check-0.4.0 \
/launcher/node_modules/truncate-utf8-bytes;.-truncate-utf8-bytes-1.0.2 \
/launcher/node_modules/tr46;.-tr46-0.0.3 \
/launcher/node_modules/token-types;.-token-types-4.2.1 \
/launcher/node_modules/to-regex-range;.-to-regex-range-5.0.1 \
/launcher/node_modules/tmp;.-tmp-0.2.3 \
/launcher/node_modules/tmp-promise;.-tmp-promise-3.0.3 \
/launcher/node_modules/tinycolor2;.-tinycolor2-1.6.0 \
/launcher/node_modules/tiny-typed-emitter;.-tiny-typed-emitter-2.1.0 \
/launcher/node_modules/timm;.-timm-1.7.1 \
/launcher/node_modules/tga;.-tga-1.0.7 \
/launcher/node_modules/tga/node_modules/ms;.-ms-2.0.0 \
/launcher/node_modules/tga/node_modules/debug;.-debug-2.6.9 \
/launcher/node_modules/text-table;.-text-table-0.2.0 \
/launcher/node_modules/temp-file;.-temp-file-3.4.0 \
/launcher/node_modules/temp-file/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/temp-file/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/temp-file/node_modules/fs-extra;.-fs-extra-10.1.0 \
/launcher/node_modules/tar;.-tar-6.2.0 \
/launcher/node_modules/supports-color;.-supports-color-7.2.0 \
/launcher/node_modules/sumchecker;.-sumchecker-3.0.1 \
/launcher/node_modules/strtok3;.-strtok3-6.3.0 \
/launcher/node_modules/strip-json-comments;.-strip-json-comments-3.1.1 \
/launcher/node_modules/strip-ansi;.-strip-ansi-6.0.1 \
/launcher/node_modules/strip-ansi-cjs;.-strip-ansi-6.0.1 \
/launcher/node_modules/string_decoder;.-string_decoder-1.3.0 \
/launcher/node_modules/string-width;.-string-width-4.2.3 \
/launcher/node_modules/string-width-cjs;.-string-width-4.2.3 \
/launcher/node_modules/stat-mode;.-stat-mode-1.0.0 \
/launcher/node_modules/spring-map-parser;.-spring-map-parser-6.1.1 \
/launcher/node_modules/source-map;.-source-map-0.6.1 \
/launcher/node_modules/source-map-support;.-source-map-support-0.5.21 \
/launcher/node_modules/simple-update-notifier;.-simple-update-notifier-2.0.0 \
/launcher/node_modules/simple-update-notifier/node_modules/semver;.-semver-7.6.0 \
/launcher/node_modules/signal-exit;.-signal-exit-3.0.7 \
/launcher/node_modules/shebang-regex;.-shebang-regex-3.0.0 \
/launcher/node_modules/shebang-command;.-shebang-command-2.0.0 \
/launcher/node_modules/set-function-length;.-set-function-length-1.2.1 \
/launcher/node_modules/semver;.-semver-6.3.1 \
/launcher/node_modules/sdfz-demo-parser;.-sdfz-demo-parser-5.11.0 \
/launcher/node_modules/sax;.-sax-1.3.0 \
/launcher/node_modules/sanitize-filename;.-sanitize-filename-1.6.3 \
/launcher/node_modules/safer-buffer;.-safer-buffer-2.1.2 \
/launcher/node_modules/safe-buffer;.-safe-buffer-5.2.1 \
/launcher/node_modules/run-parallel;.-run-parallel-1.2.0 \
/launcher/node_modules/rimraf;.-rimraf-3.0.2 \
/launcher/node_modules/reusify;.-reusify-1.0.4 \
/launcher/node_modules/retry;.-retry-0.12.0 \
/launcher/node_modules/restructure;.-restructure-2.0.1 \
/launcher/node_modules/responselike;.-responselike-2.0.1 \
/launcher/node_modules/resolve-from;.-resolve-from-4.0.0 \
/launcher/node_modules/resolve-alpn;.-resolve-alpn-1.2.1 \
/launcher/node_modules/require-directory;.-require-directory-2.1.1 \
/launcher/node_modules/regenerator-runtime;.-regenerator-runtime-0.13.11 \
/launcher/node_modules/readdirp;.-readdirp-3.6.0 \
/launcher/node_modules/readable-web-to-node-stream;.-readable-web-to-node-stream-3.0.2 \
/launcher/node_modules/readable-stream;.-readable-stream-3.6.2 \
/launcher/node_modules/read-config-file;.-read-config-file-6.3.2 \
/launcher/node_modules/quick-lru;.-quick-lru-5.1.1 \
/launcher/node_modules/queue-microtask;.-queue-microtask-1.2.3 \
/launcher/node_modules/punycode;.-punycode-2.3.1 \
/launcher/node_modules/pump;.-pump-3.0.0 \
/launcher/node_modules/promise-retry;.-promise-retry-2.0.1 \
/launcher/node_modules/progress;.-progress-2.0.3 \
/launcher/node_modules/process;.-process-0.11.10 \
/launcher/node_modules/prelude-ls;.-prelude-ls-1.2.1 \
/launcher/node_modules/pngjs;.-pngjs-6.0.0 \
/launcher/node_modules/plist;.-plist-3.1.0 \
/launcher/node_modules/pixelmatch;.-pixelmatch-4.0.2 \
/launcher/node_modules/pixelmatch/node_modules/pngjs;.-pngjs-3.4.0 \
/launcher/node_modules/picomatch;.-picomatch-2.3.1 \
/launcher/node_modules/phin;.-phin-2.9.3 \
/launcher/node_modules/pend;.-pend-1.2.0 \
/launcher/node_modules/peek-readable;.-peek-readable-4.1.0 \
/launcher/node_modules/path-scurry;.-path-scurry-1.10.1 \
/launcher/node_modules/path-scurry/node_modules/lru-cache;.-lru-cache-10.2.0 \
/launcher/node_modules/path-key;.-path-key-3.1.1 \
/launcher/node_modules/path-is-absolute;.-path-is-absolute-1.0.1 \
/launcher/node_modules/path-exists;.-path-exists-4.0.0 \
/launcher/node_modules/parse-headers;.-parse-headers-2.0.5 \
/launcher/node_modules/parse-dds;.-parse-dds-1.2.1 \
/launcher/node_modules/parse-bmfont-xml;.-parse-bmfont-xml-1.1.6 \
/launcher/node_modules/parse-bmfont-binary;.-parse-bmfont-binary-1.0.6 \
/launcher/node_modules/parse-bmfont-ascii;.-parse-bmfont-ascii-1.0.6 \
/launcher/node_modules/parent-module;.-parent-module-1.0.1 \
/launcher/node_modules/pako;.-pako-1.0.11 \
/launcher/node_modules/p-locate;.-p-locate-5.0.0 \
/launcher/node_modules/p-limit;.-p-limit-3.1.0 \
/launcher/node_modules/p-cancelable;.-p-cancelable-2.1.1 \
/launcher/node_modules/optionator;.-optionator-0.9.3 \
/launcher/node_modules/once;.-once-1.4.0 \
/launcher/node_modules/omggif;.-omggif-1.0.10 \
/launcher/node_modules/object-keys;.-object-keys-1.1.1 \
/launcher/node_modules/normalize-url;.-normalize-url-6.1.0 \
/launcher/node_modules/normalize-path;.-normalize-path-3.0.0 \
/launcher/node_modules/node-stream-zip;.-node-stream-zip-1.15.0 \
/launcher/node_modules/node-gzip;.-node-gzip-1.1.2 \
/launcher/node_modules/node-fetch;.-node-fetch-2.7.0 \
/launcher/node_modules/node-downloader-helper;.-node-downloader-helper-2.1.9 \
/launcher/node_modules/node-7z;.-node-7z-3.0.0 \
/launcher/node_modules/natural-compare;.-natural-compare-1.4.0 \
/launcher/node_modules/ms;.-ms-2.1.2 \
/launcher/node_modules/mkdirp;.-mkdirp-1.0.4 \
/launcher/node_modules/minizlib;.-minizlib-2.1.2 \
/launcher/node_modules/minizlib/node_modules/minipass;.-minipass-3.3.6 \
/launcher/node_modules/minipass;.-minipass-5.0.0 \
/launcher/node_modules/minimist;.-minimist-1.2.8 \
/launcher/node_modules/minimatch;.-minimatch-5.1.6 \
/launcher/node_modules/min-document;.-min-document-2.19.0 \
/launcher/node_modules/mimic-response;.-mimic-response-1.0.1 \
/launcher/node_modules/mime;.-mime-2.6.0 \
/launcher/node_modules/mime-types;.-mime-types-2.1.35 \
/launcher/node_modules/mime-db;.-mime-db-1.52.0 \
/launcher/node_modules/luaparse;.-luaparse-0.3.1 \
/launcher/node_modules/lru-cache;.-lru-cache-6.0.0 \
/launcher/node_modules/lowercase-keys;.-lowercase-keys-2.0.0 \
/launcher/node_modules/lodash;.-lodash-4.17.21 \
/launcher/node_modules/lodash.unset;.-lodash.unset-4.5.2 \
/launcher/node_modules/lodash.set;.-lodash.set-4.3.2 \
/launcher/node_modules/lodash.negate;.-lodash.negate-3.0.2 \
/launcher/node_modules/lodash.merge;.-lodash.merge-4.6.2 \
/launcher/node_modules/lodash.isequal;.-lodash.isequal-4.5.0 \
/launcher/node_modules/lodash.isempty;.-lodash.isempty-4.4.0 \
/launcher/node_modules/lodash.has;.-lodash.has-4.5.2 \
/launcher/node_modules/lodash.get;.-lodash.get-4.4.2 \
/launcher/node_modules/lodash.flattendeep;.-lodash.flattendeep-4.4.0 \
/launcher/node_modules/lodash.escaperegexp;.-lodash.escaperegexp-4.1.2 \
/launcher/node_modules/lodash.defaultto;.-lodash.defaultto-4.14.0 \
/launcher/node_modules/lodash.defaultsdeep;.-lodash.defaultsdeep-4.6.1 \
/launcher/node_modules/locate-path;.-locate-path-6.0.0 \
/launcher/node_modules/load-bmfont;.-load-bmfont-1.4.1 \
/launcher/node_modules/load-bmfont/node_modules/mime;.-mime-1.6.0 \
/launcher/node_modules/load-bmfont/node_modules/buffer-equal;.-buffer-equal-0.0.1 \
/launcher/node_modules/levn;.-levn-0.4.1 \
/launcher/node_modules/lazy-val;.-lazy-val-1.0.5 \
/launcher/node_modules/kysely;.-kysely-0.25.0 \
/launcher/node_modules/keyv;.-keyv-4.5.4 \
/launcher/node_modules/jsonify;.-jsonify-0.0.1 \
/launcher/node_modules/jsonfile;.-jsonfile-4.0.0 \
/launcher/node_modules/json5;.-json5-2.2.3 \
/launcher/node_modules/json-stable-stringify;.-json-stable-stringify-1.1.1 \
/launcher/node_modules/json-stable-stringify-without-jsonify;.-json-stable-stringify-without-jsonify-1.0.1 \
/launcher/node_modules/json-schema-traverse;.-json-schema-traverse-0.4.1 \
/launcher/node_modules/json-buffer;.-json-buffer-3.0.1 \
/launcher/node_modules/js-yaml;.-js-yaml-4.1.0 \
/launcher/node_modules/jpeg-js;.-jpeg-js-0.4.4 \
/launcher/node_modules/jimp;.-jimp-0.22.12 \
/launcher/node_modules/jaz-ts-utils;.-jaz-ts-utils-6.3.2 \
/launcher/node_modules/jake;.-jake-10.8.7 \
/launcher/node_modules/jake/node_modules/minimatch;.-minimatch-3.1.2 \
/launcher/node_modules/jake/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/launcher/node_modules/jackspeak;.-jackspeak-2.3.6 \
/launcher/node_modules/isomorphic-fetch;.-isomorphic-fetch-3.0.0 \
/launcher/node_modules/isexe;.-isexe-2.0.0 \
/launcher/node_modules/isbinaryfile;.-isbinaryfile-5.0.2 \
/launcher/node_modules/isarray;.-isarray-2.0.5 \
/launcher/node_modules/is-typedarray;.-is-typedarray-1.0.0 \
/launcher/node_modules/is-path-inside;.-is-path-inside-3.0.3 \
/launcher/node_modules/is-number;.-is-number-7.0.0 \
/launcher/node_modules/is-glob;.-is-glob-4.0.3 \
/launcher/node_modules/is-function;.-is-function-1.0.2 \
/launcher/node_modules/is-fullwidth-code-point;.-is-fullwidth-code-point-3.0.0 \
/launcher/node_modules/is-extglob;.-is-extglob-2.1.1 \
/launcher/node_modules/is-ci;.-is-ci-3.0.1 \
/launcher/node_modules/is-binary-path;.-is-binary-path-2.1.0 \
/launcher/node_modules/inherits;.-inherits-2.0.4 \
/launcher/node_modules/inflight;.-inflight-1.0.6 \
/launcher/node_modules/imurmurhash;.-imurmurhash-0.1.4 \
/launcher/node_modules/import-fresh;.-import-fresh-3.3.0 \
/launcher/node_modules/image-q;.-image-q-4.0.0 \
/launcher/node_modules/image-q/node_modules/@types/node;@types-node-16.9.1 \
/launcher/node_modules/ignore;.-ignore-5.3.1 \
/launcher/node_modules/ieee754;.-ieee754-1.2.1 \
/launcher/node_modules/iconv-lite;.-iconv-lite-0.6.3 \
/launcher/node_modules/https-proxy-agent;.-https-proxy-agent-5.0.1 \
/launcher/node_modules/http2-wrapper;.-http2-wrapper-1.0.3 \
/launcher/node_modules/http-proxy-agent;.-http-proxy-agent-5.0.0 \
/launcher/node_modules/http-cache-semantics;.-http-cache-semantics-4.1.1 \
/launcher/node_modules/hosted-git-info;.-hosted-git-info-4.1.0 \
/launcher/node_modules/hasown;.-hasown-2.0.1 \
/launcher/node_modules/has-symbols;.-has-symbols-1.0.3 \
/launcher/node_modules/has-proto;.-has-proto-1.0.3 \
/launcher/node_modules/has-property-descriptors;.-has-property-descriptors-1.0.2 \
/launcher/node_modules/has-flag;.-has-flag-4.0.0 \
/launcher/node_modules/graphemer;.-graphemer-1.4.0 \
/launcher/node_modules/graceful-fs;.-graceful-fs-4.2.11 \
/launcher/node_modules/got;.-got-11.8.6 \
/launcher/node_modules/gopd;.-gopd-1.0.1 \
/launcher/node_modules/globals;.-globals-13.24.0 \
/launcher/node_modules/global;.-global-4.4.0 \
/launcher/node_modules/glob;.-glob-7.2.3 \
/launcher/node_modules/glob/node_modules/minimatch;.-minimatch-3.1.2 \
/launcher/node_modules/glob/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/launcher/node_modules/glob-parent;.-glob-parent-5.1.2 \
/launcher/node_modules/gifwrap;.-gifwrap-0.10.1 \
/launcher/node_modules/get-stream;.-get-stream-5.2.0 \
/launcher/node_modules/get-intrinsic;.-get-intrinsic-1.2.4 \
/launcher/node_modules/get-caller-file;.-get-caller-file-2.0.5 \
/launcher/node_modules/function-bind;.-function-bind-1.1.2 \
/launcher/node_modules/fs.realpath;.-fs.realpath-1.0.0 \
/launcher/node_modules/fs-minipass;.-fs-minipass-2.1.0 \
/launcher/node_modules/fs-minipass/node_modules/minipass;.-minipass-3.3.6 \
/launcher/node_modules/fs-extra;.-fs-extra-8.1.0 \
/launcher/node_modules/form-data;.-form-data-4.0.0 \
/launcher/node_modules/foreground-child;.-foreground-child-3.1.1 \
/launcher/node_modules/foreground-child/node_modules/signal-exit;.-signal-exit-4.1.0 \
/launcher/node_modules/flatted;.-flatted-3.3.1 \
/launcher/node_modules/flat-cache;.-flat-cache-3.2.0 \
/launcher/node_modules/find-up;.-find-up-5.0.0 \
/launcher/node_modules/fill-range;.-fill-range-7.0.1 \
/launcher/node_modules/filelist;.-filelist-1.0.4 \
/launcher/node_modules/file-type;.-file-type-16.5.4 \
/launcher/node_modules/file-entry-cache;.-file-entry-cache-6.0.1 \
/launcher/node_modules/fd-slicer;.-fd-slicer-1.1.0 \
/launcher/node_modules/fastq;.-fastq-1.17.1 \
/launcher/node_modules/fast-levenshtein;.-fast-levenshtein-2.0.6 \
/launcher/node_modules/fast-json-stable-stringify;.-fast-json-stable-stringify-2.1.0 \
/launcher/node_modules/fast-deep-equal;.-fast-deep-equal-3.1.3 \
/launcher/node_modules/extract-zip;.-extract-zip-2.0.1 \
/launcher/node_modules/exif-parser;.-exif-parser-0.1.12 \
/launcher/node_modules/esutils;.-esutils-2.0.3 \
/launcher/node_modules/estraverse;.-estraverse-5.3.0 \
/launcher/node_modules/esrecurse;.-esrecurse-4.3.0 \
/launcher/node_modules/esquery;.-esquery-1.5.0 \
/launcher/node_modules/espree;.-espree-9.6.1 \
/launcher/node_modules/eslint;.-eslint-8.57.0 \
/launcher/node_modules/eslint/node_modules/minimatch;.-minimatch-3.1.2 \
/launcher/node_modules/eslint/node_modules/glob-parent;.-glob-parent-6.0.2 \
/launcher/node_modules/eslint/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/launcher/node_modules/eslint-visitor-keys;.-eslint-visitor-keys-3.4.3 \
/launcher/node_modules/eslint-scope;.-eslint-scope-7.2.2 \
/launcher/node_modules/escape-string-regexp;.-escape-string-regexp-4.0.0 \
/launcher/node_modules/escalade;.-escalade-3.1.2 \
/launcher/node_modules/es-errors;.-es-errors-1.3.0 \
/launcher/node_modules/es-define-property;.-es-define-property-1.0.0 \
/launcher/node_modules/err-code;.-err-code-2.0.3 \
/launcher/node_modules/env-paths;.-env-paths-2.2.1 \
/launcher/node_modules/end-of-stream;.-end-of-stream-1.4.4 \
/launcher/node_modules/emoji-regex;.-emoji-regex-8.0.0 \
/launcher/node_modules/electron;.-electron-29.1.0 \
/launcher/node_modules/electron-updater;.-electron-updater-6.1.8 \
/launcher/node_modules/electron-updater/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/electron-updater/node_modules/semver;.-semver-7.6.0 \
/launcher/node_modules/electron-updater/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/electron-updater/node_modules/fs-extra;.-fs-extra-10.1.0 \
/launcher/node_modules/electron-settings;.-electron-settings-4.0.2 \
/launcher/node_modules/electron-publish;.-electron-publish-24.9.4 \
/launcher/node_modules/electron-publish/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/electron-publish/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/electron-publish/node_modules/fs-extra;.-fs-extra-10.1.0 \
/launcher/node_modules/electron-log;.-electron-log-5.1.1 \
/launcher/node_modules/electron-builder;.-electron-builder-24.12.0 \
/launcher/node_modules/electron-builder/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/electron-builder/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/electron-builder/node_modules/fs-extra;.-fs-extra-10.1.0 \
/launcher/node_modules/ejs;.-ejs-3.1.9 \
/launcher/node_modules/eastasianwidth;.-eastasianwidth-0.2.0 \
/launcher/node_modules/dotenv;.-dotenv-9.0.2 \
/launcher/node_modules/dotenv-expand;.-dotenv-expand-5.1.0 \
/launcher/node_modules/dom-walk;.-dom-walk-0.1.2 \
/launcher/node_modules/doctrine;.-doctrine-3.0.0 \
/launcher/node_modules/dmg-builder;.-dmg-builder-24.12.0 \
/launcher/node_modules/dmg-builder/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/dmg-builder/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/dmg-builder/node_modules/fs-extra;.-fs-extra-10.1.0 \
/launcher/node_modules/discord-rpc;.-discord-rpc-4.0.1 \
/launcher/node_modules/dir-compare;.-dir-compare-3.3.0 \
/launcher/node_modules/dir-compare/node_modules/minimatch;.-minimatch-3.1.2 \
/launcher/node_modules/dir-compare/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/launcher/node_modules/delayed-stream;.-delayed-stream-1.0.0 \
/launcher/node_modules/define-data-property;.-define-data-property-1.1.4 \
/launcher/node_modules/defer-to-connect;.-defer-to-connect-2.0.1 \
/launcher/node_modules/deep-is;.-deep-is-0.1.4 \
/launcher/node_modules/decompress-response;.-decompress-response-6.0.0 \
/launcher/node_modules/decompress-response/node_modules/mimic-response;.-mimic-response-3.1.0 \
/launcher/node_modules/decode-dxt;.-decode-dxt-1.0.1 \
/launcher/node_modules/debug;.-debug-4.3.4 \
/launcher/node_modules/cross-spawn;.-cross-spawn-7.0.3 \
/launcher/node_modules/config-file-ts;.-config-file-ts-0.2.6 \
/launcher/node_modules/config-file-ts/node_modules/minimatch;.-minimatch-9.0.3 \
/launcher/node_modules/config-file-ts/node_modules/glob;.-glob-10.3.10 \
/launcher/node_modules/concat-map;.-concat-map-0.0.1 \
/launcher/node_modules/compare-version;.-compare-version-0.1.2 \
/launcher/node_modules/commander;.-commander-5.1.0 \
/launcher/node_modules/combined-stream;.-combined-stream-1.0.8 \
/launcher/node_modules/color-name;.-color-name-1.1.4 \
/launcher/node_modules/color-convert;.-color-convert-2.0.1 \
/launcher/node_modules/clone-response;.-clone-response-1.0.3 \
/launcher/node_modules/cliui;.-cliui-8.0.1 \
/launcher/node_modules/ci-info;.-ci-info-3.9.0 \
/launcher/node_modules/chromium-pickle-js;.-chromium-pickle-js-0.2.0 \
/launcher/node_modules/chownr;.-chownr-2.0.0 \
/launcher/node_modules/chokidar;.-chokidar-3.6.0 \
/launcher/node_modules/chalk;.-chalk-4.1.2 \
/launcher/node_modules/callsites;.-callsites-3.1.0 \
/launcher/node_modules/call-bind;.-call-bind-1.0.7 \
/launcher/node_modules/cacheable-request;.-cacheable-request-7.0.4 \
/launcher/node_modules/cacheable-lookup;.-cacheable-lookup-5.0.4 \
/launcher/node_modules/builder-util;.-builder-util-24.9.4 \
/launcher/node_modules/builder-util/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/builder-util/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/builder-util/node_modules/fs-extra;.-fs-extra-10.1.0 \
/launcher/node_modules/builder-util/node_modules/7zip-bin;.-7zip-bin-5.2.0 \
/launcher/node_modules/builder-util-runtime;.-builder-util-runtime-9.2.3 \
/launcher/node_modules/buffer;.-buffer-5.7.1 \
/launcher/node_modules/buffer-from;.-buffer-from-1.1.2 \
/launcher/node_modules/buffer-equal;.-buffer-equal-1.0.1 \
/launcher/node_modules/buffer-crc32;.-buffer-crc32-0.2.13 \
/launcher/node_modules/braces;.-braces-3.0.2 \
/launcher/node_modules/brace-expansion;.-brace-expansion-2.0.1 \
/launcher/node_modules/bmp-js;.-bmp-js-0.1.0 \
/launcher/node_modules/bluebird;.-bluebird-3.7.2 \
/launcher/node_modules/bluebird-lst;.-bluebird-lst-1.0.9 \
/launcher/node_modules/binary-extensions;.-binary-extensions-2.2.0 \
/launcher/node_modules/base64-js;.-base64-js-1.5.1 \
/launcher/node_modules/balanced-match;.-balanced-match-1.0.2 \
/launcher/node_modules/at-least-node;.-at-least-node-1.0.0 \
/launcher/node_modules/asynckit;.-asynckit-0.4.0 \
/launcher/node_modules/async;.-async-3.2.5 \
/launcher/node_modules/async-exit-hook;.-async-exit-hook-2.0.1 \
/launcher/node_modules/argparse;.-argparse-2.0.1 \
/launcher/node_modules/app-builder-lib;.-app-builder-lib-24.12.0 \
/launcher/node_modules/app-builder-lib/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/app-builder-lib/node_modules/semver;.-semver-7.6.0 \
/launcher/node_modules/app-builder-lib/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/app-builder-lib/node_modules/fs-extra;.-fs-extra-10.1.0 \
/launcher/node_modules/app-builder-bin;.-app-builder-bin-4.0.0 \
/launcher/node_modules/anymatch;.-anymatch-3.1.3 \
/launcher/node_modules/any-base;.-any-base-1.1.0 \
/launcher/node_modules/ansi-styles;.-ansi-styles-4.3.0 \
/launcher/node_modules/ansi-regex;.-ansi-regex-5.0.1 \
/launcher/node_modules/ajv;.-ajv-6.12.6 \
/launcher/node_modules/ajv-keywords;.-ajv-keywords-3.5.2 \
/launcher/node_modules/agent-base;.-agent-base-6.0.2 \
/launcher/node_modules/acorn;.-acorn-8.11.3 \
/launcher/node_modules/acorn-jsx;.-acorn-jsx-5.3.2 \
/launcher/node_modules/@xmldom/xmldom;@xmldom-xmldom-0.8.10 \
/launcher/node_modules/@ungap/structured-clone;@ungap-structured-clone-1.2.0 \
/launcher/node_modules/@types/responselike;@types-responselike-1.0.3 \
/launcher/node_modules/@types/node;@types-node-20.11.24 \
/launcher/node_modules/@types/ms;@types-ms-0.7.34 \
/launcher/node_modules/@types/keyv;@types-keyv-3.1.4 \
/launcher/node_modules/@types/http-cache-semantics;@types-http-cache-semantics-4.0.4 \
/launcher/node_modules/@types/fs-extra;@types-fs-extra-9.0.13 \
/launcher/node_modules/@types/debug;@types-debug-4.1.12 \
/launcher/node_modules/@types/cacheable-request;@types-cacheable-request-6.0.3 \
/launcher/node_modules/@tootallnate/once;@tootallnate-once-2.0.0 \
/launcher/node_modules/@tokenizer/token;@tokenizer-token-0.3.0 \
/launcher/node_modules/@szmarczak/http-timer;@szmarczak-http-timer-4.0.6 \
/launcher/node_modules/@sindresorhus/is;@sindresorhus-is-4.6.0 \
/launcher/node_modules/@nodelib/fs.walk;@nodelib-fs.walk-1.2.8 \
/launcher/node_modules/@nodelib/fs.stat;@nodelib-fs.stat-2.0.5 \
/launcher/node_modules/@nodelib/fs.scandir;@nodelib-fs.scandir-2.1.5 \
/launcher/node_modules/@malept/flatpak-bundler;@malept-flatpak-bundler-0.4.0 \
/launcher/node_modules/@malept/flatpak-bundler/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/@malept/flatpak-bundler/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/@malept/flatpak-bundler/node_modules/fs-extra;.-fs-extra-9.1.0 \
/launcher/node_modules/@malept/cross-spawn-promise;@malept-cross-spawn-promise-1.1.1 \
/launcher/node_modules/@jimp/utils;@jimp-utils-0.22.12 \
/launcher/node_modules/@jimp/types;@jimp-types-0.22.12 \
/launcher/node_modules/@jimp/tiff;@jimp-tiff-0.22.12 \
/launcher/node_modules/@jimp/png;@jimp-png-0.22.12 \
/launcher/node_modules/@jimp/plugins;@jimp-plugins-0.22.12 \
/launcher/node_modules/@jimp/plugin-threshold;@jimp-plugin-threshold-0.22.12 \
/launcher/node_modules/@jimp/plugin-shadow;@jimp-plugin-shadow-0.22.12 \
/launcher/node_modules/@jimp/plugin-scale;@jimp-plugin-scale-0.22.12 \
/launcher/node_modules/@jimp/plugin-rotate;@jimp-plugin-rotate-0.22.12 \
/launcher/node_modules/@jimp/plugin-resize;@jimp-plugin-resize-0.22.12 \
/launcher/node_modules/@jimp/plugin-print;@jimp-plugin-print-0.22.12 \
/launcher/node_modules/@jimp/plugin-normalize;@jimp-plugin-normalize-0.22.12 \
/launcher/node_modules/@jimp/plugin-mask;@jimp-plugin-mask-0.22.12 \
/launcher/node_modules/@jimp/plugin-invert;@jimp-plugin-invert-0.22.12 \
/launcher/node_modules/@jimp/plugin-gaussian;@jimp-plugin-gaussian-0.22.12 \
/launcher/node_modules/@jimp/plugin-flip;@jimp-plugin-flip-0.22.12 \
/launcher/node_modules/@jimp/plugin-fisheye;@jimp-plugin-fisheye-0.22.12 \
/launcher/node_modules/@jimp/plugin-dither;@jimp-plugin-dither-0.22.12 \
/launcher/node_modules/@jimp/plugin-displace;@jimp-plugin-displace-0.22.12 \
/launcher/node_modules/@jimp/plugin-crop;@jimp-plugin-crop-0.22.12 \
/launcher/node_modules/@jimp/plugin-cover;@jimp-plugin-cover-0.22.12 \
/launcher/node_modules/@jimp/plugin-contain;@jimp-plugin-contain-0.22.12 \
/launcher/node_modules/@jimp/plugin-color;@jimp-plugin-color-0.22.12 \
/launcher/node_modules/@jimp/plugin-circle;@jimp-plugin-circle-0.22.12 \
/launcher/node_modules/@jimp/plugin-blur;@jimp-plugin-blur-0.22.12 \
/launcher/node_modules/@jimp/plugin-blit;@jimp-plugin-blit-0.22.12 \
/launcher/node_modules/@jimp/jpeg;@jimp-jpeg-0.22.12 \
/launcher/node_modules/@jimp/gif;@jimp-gif-0.22.12 \
/launcher/node_modules/@jimp/custom;@jimp-custom-0.22.12 \
/launcher/node_modules/@jimp/core;@jimp-core-0.22.12 \
/launcher/node_modules/@jimp/bmp;@jimp-bmp-0.22.12 \
/launcher/node_modules/@isaacs/cliui;@isaacs-cliui-8.0.2 \
/launcher/node_modules/@isaacs/cliui/node_modules/wrap-ansi;.-wrap-ansi-8.1.0 \
/launcher/node_modules/@isaacs/cliui/node_modules/strip-ansi;.-strip-ansi-7.1.0 \
/launcher/node_modules/@isaacs/cliui/node_modules/string-width;.-string-width-5.1.2 \
/launcher/node_modules/@isaacs/cliui/node_modules/emoji-regex;.-emoji-regex-9.2.2 \
/launcher/node_modules/@isaacs/cliui/node_modules/ansi-styles;.-ansi-styles-6.2.1 \
/launcher/node_modules/@isaacs/cliui/node_modules/ansi-regex;.-ansi-regex-6.0.1 \
/launcher/node_modules/@humanwhocodes/object-schema;@humanwhocodes-object-schema-2.0.2 \
/launcher/node_modules/@humanwhocodes/module-importer;@humanwhocodes-module-importer-1.0.1 \
/launcher/node_modules/@humanwhocodes/config-array;@humanwhocodes-config-array-0.11.14 \
/launcher/node_modules/@humanwhocodes/config-array/node_modules/minimatch;.-minimatch-3.1.2 \
/launcher/node_modules/@humanwhocodes/config-array/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/launcher/node_modules/@eslint/js;@eslint-js-8.57.0 \
/launcher/node_modules/@eslint/eslintrc;@eslint-eslintrc-2.1.4 \
/launcher/node_modules/@eslint/eslintrc/node_modules/minimatch;.-minimatch-3.1.2 \
/launcher/node_modules/@eslint/eslintrc/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/launcher/node_modules/@eslint-community/regexpp;@eslint-community-regexpp-4.10.0 \
/launcher/node_modules/@eslint-community/eslint-utils;@eslint-community-eslint-utils-4.4.0 \
/launcher/node_modules/@electron/universal;@electron-universal-1.4.1 \
/launcher/node_modules/@electron/universal/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/@electron/universal/node_modules/minimatch;.-minimatch-3.1.2 \
/launcher/node_modules/@electron/universal/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/@electron/universal/node_modules/fs-extra;.-fs-extra-9.1.0 \
/launcher/node_modules/@electron/universal/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/launcher/node_modules/@electron/remote;@electron-remote-2.1.2 \
/launcher/node_modules/@electron/osx-sign;@electron-osx-sign-1.0.5 \
/launcher/node_modules/@electron/osx-sign/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/@electron/osx-sign/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/@electron/osx-sign/node_modules/isbinaryfile;.-isbinaryfile-4.0.10 \
/launcher/node_modules/@electron/osx-sign/node_modules/fs-extra;.-fs-extra-10.1.0 \
/launcher/node_modules/@electron/notarize;@electron-notarize-2.1.0 \
/launcher/node_modules/@electron/notarize/node_modules/universalify;.-universalify-2.0.1 \
/launcher/node_modules/@electron/notarize/node_modules/jsonfile;.-jsonfile-6.1.0 \
/launcher/node_modules/@electron/notarize/node_modules/fs-extra;.-fs-extra-9.1.0 \
/launcher/node_modules/@electron/get;@electron-get-2.0.3 \
/launcher/node_modules/@electron/asar;@electron-asar-3.2.8 \
/launcher/node_modules/@electron/asar/node_modules/minimatch;.-minimatch-3.1.2 \
/launcher/node_modules/@electron/asar/node_modules/brace-expansion;.-brace-expansion-1.1.11 \
/launcher/node_modules/@develar/schema-utils;@develar-schema-utils-2.6.5 \
/launcher/node_modules/@aashutoshrathi/word-wrap;@aashutoshrathi-word-wrap-1.2.6 \
/launcher/node_modules/7zip-min;.-7zip-min-1.4.4 \
/launcher/node_modules/7zip-bin;.-7zip-bin-5.1.1 \

