# make modnpm-gen-modules > modules.inc
# MODNPM_OMITDEV=No 
# MODNPM_OMITOPTIONAL=Yes
# MODNPM_INCLUDES=
# MODNPM_EXCLUDES=
DIST_TUPLE += \
npm . 7zip-bin 5.1.1 . \
npm . 7zip-bin 5.2.0 . \
npm . 7zip-min 1.4.4 . \
npm . acorn 8.11.3 . \
npm . acorn-jsx 5.3.2 . \
npm . agent-base 6.0.2 . \
npm . ajv 6.12.6 . \
npm . ajv-keywords 3.5.2 . \
npm . ansi-regex 5.0.1 . \
npm . ansi-regex 6.0.1 . \
npm . ansi-styles 4.3.0 . \
npm . ansi-styles 6.2.1 . \
npm . any-base 1.1.0 . \
npm . anymatch 3.1.3 . \
npm . app-builder-bin 4.0.0 . \
npm . app-builder-lib 24.12.0 . \
npm . argparse 2.0.1 . \
npm . async 3.2.5 . \
npm . async-exit-hook 2.0.1 . \
npm . asynckit 0.4.0 . \
npm . at-least-node 1.0.0 . \
npm . balanced-match 1.0.2 . \
npm . base64-js 1.5.1 . \
npm . binary-extensions 2.2.0 . \
npm . bluebird 3.7.2 . \
npm . bluebird-lst 1.0.9 . \
npm . bmp-js 0.1.0 . \
npm . brace-expansion 1.1.11 . \
npm . brace-expansion 2.0.1 . \
npm . braces 3.0.2 . \
npm . buffer 5.7.1 . \
npm . buffer-crc32 0.2.13 . \
npm . buffer-equal 0.0.1 . \
npm . buffer-equal 1.0.1 . \
npm . buffer-from 1.1.2 . \
npm . builder-util 24.9.4 . \
npm . builder-util-runtime 9.2.3 . \
npm . cacheable-lookup 5.0.4 . \
npm . cacheable-request 7.0.4 . \
npm . call-bind 1.0.7 . \
npm . callsites 3.1.0 . \
npm . chalk 4.1.2 . \
npm . chokidar 3.6.0 . \
npm . chownr 2.0.0 . \
npm . chromium-pickle-js 0.2.0 . \
npm . ci-info 3.9.0 . \
npm . cliui 8.0.1 . \
npm . clone-response 1.0.3 . \
npm . color-convert 2.0.1 . \
npm . color-name 1.1.4 . \
npm . combined-stream 1.0.8 . \
npm . commander 5.1.0 . \
npm . compare-version 0.1.2 . \
npm . concat-map 0.0.1 . \
npm . config-file-ts 0.2.6 . \
npm . cross-spawn 7.0.3 . \
npm . debug 2.6.9 . \
npm . debug 4.3.4 . \
npm . decode-dxt 1.0.1 . \
npm . decompress-response 6.0.0 . \
npm . deep-is 0.1.4 . \
npm . defer-to-connect 2.0.1 . \
npm . define-data-property 1.1.4 . \
npm . delayed-stream 1.0.0 . \
npm . dir-compare 3.3.0 . \
npm . discord-rpc 4.0.1 . \
npm . dmg-builder 24.12.0 . \
npm . doctrine 3.0.0 . \
npm . dom-walk 0.1.2 . \
npm . dotenv 9.0.2 . \
npm . dotenv-expand 5.1.0 . \
npm . eastasianwidth 0.2.0 . \
npm . ejs 3.1.9 . \
npm . electron 29.1.0 . \
npm . electron-builder 24.12.0 . \
npm . electron-log 5.1.1 . \
npm . electron-publish 24.9.4 . \
npm . electron-settings 4.0.2 . \
npm . electron-updater 6.1.8 . \
npm . emoji-regex 8.0.0 . \
npm . emoji-regex 9.2.2 . \
npm . end-of-stream 1.4.4 . \
npm . env-paths 2.2.1 . \
npm . err-code 2.0.3 . \
npm . es-define-property 1.0.0 . \
npm . es-errors 1.3.0 . \
npm . escalade 3.1.2 . \
npm . escape-string-regexp 4.0.0 . \
npm . eslint 8.57.0 . \
npm . eslint-scope 7.2.2 . \
npm . eslint-visitor-keys 3.4.3 . \
npm . espree 9.6.1 . \
npm . esquery 1.5.0 . \
npm . esrecurse 4.3.0 . \
npm . estraverse 5.3.0 . \
npm . esutils 2.0.3 . \
npm . exif-parser 0.1.12 . \
npm . extract-zip 2.0.1 . \
npm . fast-deep-equal 3.1.3 . \
npm . fast-json-stable-stringify 2.1.0 . \
npm . fast-levenshtein 2.0.6 . \
npm . fastq 1.17.1 . \
npm . fd-slicer 1.1.0 . \
npm . file-entry-cache 6.0.1 . \
npm . file-type 16.5.4 . \
npm . filelist 1.0.4 . \
npm . fill-range 7.0.1 . \
npm . find-up 5.0.0 . \
npm . flat-cache 3.2.0 . \
npm . flatted 3.3.1 . \
npm . foreground-child 3.1.1 . \
npm . form-data 4.0.0 . \
npm . fs-extra 10.1.0 . \
npm . fs-extra 8.1.0 . \
npm . fs-extra 9.1.0 . \
npm . fs-minipass 2.1.0 . \
npm . fs.realpath 1.0.0 . \
npm . function-bind 1.1.2 . \
npm . get-caller-file 2.0.5 . \
npm . get-intrinsic 1.2.4 . \
npm . get-stream 5.2.0 . \
npm . gifwrap 0.10.1 . \
npm . glob 10.3.10 . \
npm . glob 7.2.3 . \
npm . glob-parent 5.1.2 . \
npm . glob-parent 6.0.2 . \
npm . global 4.4.0 . \
npm . globals 13.24.0 . \
npm . gopd 1.0.1 . \
npm . got 11.8.6 . \
npm . graceful-fs 4.2.11 . \
npm . graphemer 1.4.0 . \
npm . has-flag 4.0.0 . \
npm . has-property-descriptors 1.0.2 . \
npm . has-proto 1.0.3 . \
npm . has-symbols 1.0.3 . \
npm . hasown 2.0.1 . \
npm . hosted-git-info 4.1.0 . \
npm . http-cache-semantics 4.1.1 . \
npm . http-proxy-agent 5.0.0 . \
npm . http2-wrapper 1.0.3 . \
npm . https-proxy-agent 5.0.1 . \
npm . iconv-lite 0.6.3 . \
npm . ieee754 1.2.1 . \
npm . ignore 5.3.1 . \
npm . image-q 4.0.0 . \
npm . import-fresh 3.3.0 . \
npm . imurmurhash 0.1.4 . \
npm . inflight 1.0.6 . \
npm . inherits 2.0.4 . \
npm . is-binary-path 2.1.0 . \
npm . is-ci 3.0.1 . \
npm . is-extglob 2.1.1 . \
npm . is-fullwidth-code-point 3.0.0 . \
npm . is-function 1.0.2 . \
npm . is-glob 4.0.3 . \
npm . is-number 7.0.0 . \
npm . is-path-inside 3.0.3 . \
npm . is-typedarray 1.0.0 . \
npm . isarray 2.0.5 . \
npm . isbinaryfile 4.0.10 . \
npm . isbinaryfile 5.0.2 . \
npm . isexe 2.0.0 . \
npm . isomorphic-fetch 3.0.0 . \
npm . jackspeak 2.3.6 . \
npm . jake 10.8.7 . \
npm . jaz-ts-utils 6.3.2 . \
npm . jimp 0.22.12 . \
npm . jpeg-js 0.4.4 . \
npm . js-yaml 4.1.0 . \
npm . json-buffer 3.0.1 . \
npm . json-schema-traverse 0.4.1 . \
npm . json-stable-stringify 1.1.1 . \
npm . json-stable-stringify-without-jsonify 1.0.1 . \
npm . json5 2.2.3 . \
npm . jsonfile 4.0.0 . \
npm . jsonfile 6.1.0 . \
npm . jsonify 0.0.1 . \
npm . keyv 4.5.4 . \
npm . kysely 0.25.0 . \
npm . lazy-val 1.0.5 . \
npm . levn 0.4.1 . \
npm . load-bmfont 1.4.1 . \
npm . locate-path 6.0.0 . \
npm . lodash 4.17.21 . \
npm . lodash.defaultsdeep 4.6.1 . \
npm . lodash.defaultto 4.14.0 . \
npm . lodash.escaperegexp 4.1.2 . \
npm . lodash.flattendeep 4.4.0 . \
npm . lodash.get 4.4.2 . \
npm . lodash.has 4.5.2 . \
npm . lodash.isempty 4.4.0 . \
npm . lodash.isequal 4.5.0 . \
npm . lodash.merge 4.6.2 . \
npm . lodash.negate 3.0.2 . \
npm . lodash.set 4.3.2 . \
npm . lodash.unset 4.5.2 . \
npm . lowercase-keys 2.0.0 . \
npm . lru-cache 10.2.0 . \
npm . lru-cache 6.0.0 . \
npm . luaparse 0.3.1 . \
npm . mime 1.6.0 . \
npm . mime 2.6.0 . \
npm . mime-db 1.52.0 . \
npm . mime-types 2.1.35 . \
npm . mimic-response 1.0.1 . \
npm . mimic-response 3.1.0 . \
npm . min-document 2.19.0 . \
npm . minimatch 3.1.2 . \
npm . minimatch 5.1.6 . \
npm . minimatch 9.0.3 . \
npm . minimist 1.2.8 . \
npm . minipass 3.3.6 . \
npm . minipass 5.0.0 . \
npm . minizlib 2.1.2 . \
npm . mkdirp 1.0.4 . \
npm . ms 2.0.0 . \
npm . ms 2.1.2 . \
npm . natural-compare 1.4.0 . \
npm . node-7z 3.0.0 . \
npm . node-downloader-helper 2.1.9 . \
npm . node-fetch 2.7.0 . \
npm . node-gzip 1.1.2 . \
npm . node-stream-zip 1.15.0 . \
npm . normalize-path 3.0.0 . \
npm . normalize-url 6.1.0 . \
npm . object-keys 1.1.1 . \
npm . omggif 1.0.10 . \
npm . once 1.4.0 . \
npm . optionator 0.9.3 . \
npm . p-cancelable 2.1.1 . \
npm . p-limit 3.1.0 . \
npm . p-locate 5.0.0 . \
npm . pako 1.0.11 . \
npm . parent-module 1.0.1 . \
npm . parse-bmfont-ascii 1.0.6 . \
npm . parse-bmfont-binary 1.0.6 . \
npm . parse-bmfont-xml 1.1.6 . \
npm . parse-dds 1.2.1 . \
npm . parse-headers 2.0.5 . \
npm . path-exists 4.0.0 . \
npm . path-is-absolute 1.0.1 . \
npm . path-key 3.1.1 . \
npm . path-scurry 1.10.1 . \
npm . peek-readable 4.1.0 . \
npm . pend 1.2.0 . \
npm . phin 2.9.3 . \
npm . picomatch 2.3.1 . \
npm . pixelmatch 4.0.2 . \
npm . plist 3.1.0 . \
npm . pngjs 3.4.0 . \
npm . pngjs 6.0.0 . \
npm . prelude-ls 1.2.1 . \
npm . process 0.11.10 . \
npm . progress 2.0.3 . \
npm . promise-retry 2.0.1 . \
npm . pump 3.0.0 . \
npm . punycode 2.3.1 . \
npm . queue-microtask 1.2.3 . \
npm . quick-lru 5.1.1 . \
npm . read-config-file 6.3.2 . \
npm . readable-stream 3.6.2 . \
npm . readable-web-to-node-stream 3.0.2 . \
npm . readdirp 3.6.0 . \
npm . regenerator-runtime 0.13.11 . \
npm . require-directory 2.1.1 . \
npm . resolve-alpn 1.2.1 . \
npm . resolve-from 4.0.0 . \
npm . responselike 2.0.1 . \
npm . restructure 2.0.1 . \
npm . retry 0.12.0 . \
npm . reusify 1.0.4 . \
npm . rimraf 3.0.2 . \
npm . run-parallel 1.2.0 . \
npm . safe-buffer 5.2.1 . \
npm . safer-buffer 2.1.2 . \
npm . sanitize-filename 1.6.3 . \
npm . sax 1.3.0 . \
npm . sdfz-demo-parser 5.11.0 . \
npm . semver 6.3.1 . \
npm . semver 7.6.0 . \
npm . set-function-length 1.2.1 . \
npm . shebang-command 2.0.0 . \
npm . shebang-regex 3.0.0 . \
npm . signal-exit 3.0.7 . \
npm . signal-exit 4.1.0 . \
npm . simple-update-notifier 2.0.0 . \
npm . source-map 0.6.1 . \
npm . source-map-support 0.5.21 . \
npm . spring-map-parser 6.1.1 . \
npm . stat-mode 1.0.0 . \
npm . string-width 4.2.3 . \
npm . string-width 5.1.2 . \
npm . string_decoder 1.3.0 . \
npm . strip-ansi 6.0.1 . \
npm . strip-ansi 7.1.0 . \
npm . strip-json-comments 3.1.1 . \
npm . strtok3 6.3.0 . \
npm . sumchecker 3.0.1 . \
npm . supports-color 7.2.0 . \
npm . tar 6.2.0 . \
npm . temp-file 3.4.0 . \
npm . text-table 0.2.0 . \
npm . tga 1.0.7 . \
npm . timm 1.7.1 . \
npm . tiny-typed-emitter 2.1.0 . \
npm . tinycolor2 1.6.0 . \
npm . tmp 0.2.3 . \
npm . tmp-promise 3.0.3 . \
npm . to-regex-range 5.0.1 . \
npm . token-types 4.2.1 . \
npm . tr46 0.0.3 . \
npm . truncate-utf8-bytes 1.0.2 . \
npm . type-check 0.4.0 . \
npm . type-fest 0.20.2 . \
npm . typedarray-to-buffer 3.1.5 . \
npm . typescript 5.3.3 . \
npm . undici-types 5.26.5 . \
npm . universalify 0.1.2 . \
npm . universalify 2.0.1 . \
npm . uri-js 4.4.1 . \
npm . utf8-byte-length 1.0.4 . \
npm . utif2 4.1.0 . \
npm . util-deprecate 1.0.2 . \
npm . webidl-conversions 3.0.1 . \
npm . whatwg-fetch 3.6.20 . \
npm . whatwg-url 5.0.0 . \
npm . which 2.0.2 . \
npm . wrap-ansi 7.0.0 . \
npm . wrap-ansi 8.1.0 . \
npm . wrappy 1.0.2 . \
npm . write-file-atomic 3.0.3 . \
npm . ws 7.5.9 . \
npm . xhr 2.6.0 . \
npm . xml-parse-from-string 1.0.1 . \
npm . xml2js 0.5.0 . \
npm . xmlbuilder 11.0.1 . \
npm . xmlbuilder 15.1.1 . \
npm . xtend 4.0.2 . \
npm . y18n 5.0.8 . \
npm . yallist 4.0.0 . \
npm . yargs 17.7.2 . \
npm . yargs-parser 21.1.1 . \
npm . yauzl 2.10.0 . \
npm . yocto-queue 0.1.0 . \
npm @aashutoshrathi word-wrap 1.2.6 . \
npm @develar schema-utils 2.6.5 . \
npm @electron asar 3.2.8 . \
npm @electron get 2.0.3 . \
npm @electron notarize 2.1.0 . \
npm @electron osx-sign 1.0.5 . \
npm @electron remote 2.1.2 . \
npm @electron universal 1.4.1 . \
npm @eslint eslintrc 2.1.4 . \
npm @eslint js 8.57.0 . \
npm @eslint-community eslint-utils 4.4.0 . \
npm @eslint-community regexpp 4.10.0 . \
npm @humanwhocodes config-array 0.11.14 . \
npm @humanwhocodes module-importer 1.0.1 . \
npm @humanwhocodes object-schema 2.0.2 . \
npm @isaacs cliui 8.0.2 . \
npm @jimp bmp 0.22.12 . \
npm @jimp core 0.22.12 . \
npm @jimp custom 0.22.12 . \
npm @jimp gif 0.22.12 . \
npm @jimp jpeg 0.22.12 . \
npm @jimp plugin-blit 0.22.12 . \
npm @jimp plugin-blur 0.22.12 . \
npm @jimp plugin-circle 0.22.12 . \
npm @jimp plugin-color 0.22.12 . \
npm @jimp plugin-contain 0.22.12 . \
npm @jimp plugin-cover 0.22.12 . \
npm @jimp plugin-crop 0.22.12 . \
npm @jimp plugin-displace 0.22.12 . \
npm @jimp plugin-dither 0.22.12 . \
npm @jimp plugin-fisheye 0.22.12 . \
npm @jimp plugin-flip 0.22.12 . \
npm @jimp plugin-gaussian 0.22.12 . \
npm @jimp plugin-invert 0.22.12 . \
npm @jimp plugin-mask 0.22.12 . \
npm @jimp plugin-normalize 0.22.12 . \
npm @jimp plugin-print 0.22.12 . \
npm @jimp plugin-resize 0.22.12 . \
npm @jimp plugin-rotate 0.22.12 . \
npm @jimp plugin-scale 0.22.12 . \
npm @jimp plugin-shadow 0.22.12 . \
npm @jimp plugin-threshold 0.22.12 . \
npm @jimp plugins 0.22.12 . \
npm @jimp png 0.22.12 . \
npm @jimp tiff 0.22.12 . \
npm @jimp types 0.22.12 . \
npm @jimp utils 0.22.12 . \
npm @malept cross-spawn-promise 1.1.1 . \
npm @malept flatpak-bundler 0.4.0 . \
npm @nodelib fs.scandir 2.1.5 . \
npm @nodelib fs.stat 2.0.5 . \
npm @nodelib fs.walk 1.2.8 . \
npm @sindresorhus is 4.6.0 . \
npm @szmarczak http-timer 4.0.6 . \
npm @tokenizer token 0.3.0 . \
npm @tootallnate once 2.0.0 . \
npm @types cacheable-request 6.0.3 . \
npm @types debug 4.1.12 . \
npm @types fs-extra 9.0.13 . \
npm @types http-cache-semantics 4.0.4 . \
npm @types keyv 3.1.4 . \
npm @types ms 0.7.34 . \
npm @types node 16.9.1 . \
npm @types node 20.11.24 . \
npm @types responselike 1.0.3 . \
npm @ungap structured-clone 1.2.0 . \
npm @xmldom xmldom 0.8.10 . \

MODNPM_MV += \
.-7zip-bin-5.1.1 .npm/.-7zip-bin-5.1.1 \
.-7zip-bin-5.2.0 .npm/.-7zip-bin-5.2.0 \
.-7zip-min-1.4.4 node_modules/7zip-min \
.-acorn-8.11.3 node_modules/acorn \
.-acorn-jsx-5.3.2 node_modules/acorn-jsx \
.-agent-base-6.0.2 node_modules/agent-base \
.-ajv-6.12.6 node_modules/ajv \
.-ajv-keywords-3.5.2 node_modules/ajv-keywords \
.-ansi-regex-5.0.1 .npm/.-ansi-regex-5.0.1 \
.-ansi-regex-6.0.1 .npm/.-ansi-regex-6.0.1 \
.-ansi-styles-4.3.0 .npm/.-ansi-styles-4.3.0 \
.-ansi-styles-6.2.1 .npm/.-ansi-styles-6.2.1 \
.-any-base-1.1.0 node_modules/any-base \
.-anymatch-3.1.3 node_modules/anymatch \
.-app-builder-bin-4.0.0 node_modules/app-builder-bin \
.-app-builder-lib-24.12.0 node_modules/app-builder-lib \
.-argparse-2.0.1 node_modules/argparse \
.-async-3.2.5 node_modules/async \
.-async-exit-hook-2.0.1 node_modules/async-exit-hook \
.-asynckit-0.4.0 node_modules/asynckit \
.-at-least-node-1.0.0 node_modules/at-least-node \
.-balanced-match-1.0.2 node_modules/balanced-match \
.-base64-js-1.5.1 node_modules/base64-js \
.-binary-extensions-2.2.0 node_modules/binary-extensions \
.-bluebird-3.7.2 node_modules/bluebird \
.-bluebird-lst-1.0.9 node_modules/bluebird-lst \
.-bmp-js-0.1.0 node_modules/bmp-js \
.-brace-expansion-1.1.11 .npm/.-brace-expansion-1.1.11 \
.-brace-expansion-2.0.1 .npm/.-brace-expansion-2.0.1 \
.-braces-3.0.2 node_modules/braces \
.-buffer-5.7.1 node_modules/buffer \
.-buffer-crc32-0.2.13 node_modules/buffer-crc32 \
.-buffer-equal-0.0.1 .npm/.-buffer-equal-0.0.1 \
.-buffer-equal-1.0.1 .npm/.-buffer-equal-1.0.1 \
.-buffer-from-1.1.2 node_modules/buffer-from \
.-builder-util-24.9.4 node_modules/builder-util \
.-builder-util-runtime-9.2.3 node_modules/builder-util-runtime \
.-cacheable-lookup-5.0.4 node_modules/cacheable-lookup \
.-cacheable-request-7.0.4 node_modules/cacheable-request \
.-call-bind-1.0.7 node_modules/call-bind \
.-callsites-3.1.0 node_modules/callsites \
.-chalk-4.1.2 node_modules/chalk \
.-chokidar-3.6.0 node_modules/chokidar \
.-chownr-2.0.0 node_modules/chownr \
.-chromium-pickle-js-0.2.0 node_modules/chromium-pickle-js \
.-ci-info-3.9.0 node_modules/ci-info \
.-cliui-8.0.1 node_modules/cliui \
.-clone-response-1.0.3 node_modules/clone-response \
.-color-convert-2.0.1 node_modules/color-convert \
.-color-name-1.1.4 node_modules/color-name \
.-combined-stream-1.0.8 node_modules/combined-stream \
.-commander-5.1.0 node_modules/commander \
.-compare-version-0.1.2 node_modules/compare-version \
.-concat-map-0.0.1 node_modules/concat-map \
.-config-file-ts-0.2.6 node_modules/config-file-ts \
.-cross-spawn-7.0.3 node_modules/cross-spawn \
.-debug-2.6.9 .npm/.-debug-2.6.9 \
.-debug-4.3.4 .npm/.-debug-4.3.4 \
.-decode-dxt-1.0.1 node_modules/decode-dxt \
.-decompress-response-6.0.0 node_modules/decompress-response \
.-deep-is-0.1.4 node_modules/deep-is \
.-defer-to-connect-2.0.1 node_modules/defer-to-connect \
.-define-data-property-1.1.4 node_modules/define-data-property \
.-delayed-stream-1.0.0 node_modules/delayed-stream \
.-dir-compare-3.3.0 node_modules/dir-compare \
.-discord-rpc-4.0.1 node_modules/discord-rpc \
.-dmg-builder-24.12.0 node_modules/dmg-builder \
.-doctrine-3.0.0 node_modules/doctrine \
.-dom-walk-0.1.2 node_modules/dom-walk \
.-dotenv-9.0.2 node_modules/dotenv \
.-dotenv-expand-5.1.0 node_modules/dotenv-expand \
.-eastasianwidth-0.2.0 node_modules/eastasianwidth \
.-ejs-3.1.9 node_modules/ejs \
.-electron-29.1.0 node_modules/electron \
.-electron-builder-24.12.0 node_modules/electron-builder \
.-electron-log-5.1.1 node_modules/electron-log \
.-electron-publish-24.9.4 node_modules/electron-publish \
.-electron-settings-4.0.2 node_modules/electron-settings \
.-electron-updater-6.1.8 node_modules/electron-updater \
.-emoji-regex-8.0.0 .npm/.-emoji-regex-8.0.0 \
.-emoji-regex-9.2.2 .npm/.-emoji-regex-9.2.2 \
.-end-of-stream-1.4.4 node_modules/end-of-stream \
.-env-paths-2.2.1 node_modules/env-paths \
.-err-code-2.0.3 node_modules/err-code \
.-es-define-property-1.0.0 node_modules/es-define-property \
.-es-errors-1.3.0 node_modules/es-errors \
.-escalade-3.1.2 node_modules/escalade \
.-escape-string-regexp-4.0.0 node_modules/escape-string-regexp \
.-eslint-8.57.0 node_modules/eslint \
.-eslint-scope-7.2.2 node_modules/eslint-scope \
.-eslint-visitor-keys-3.4.3 node_modules/eslint-visitor-keys \
.-espree-9.6.1 node_modules/espree \
.-esquery-1.5.0 node_modules/esquery \
.-esrecurse-4.3.0 node_modules/esrecurse \
.-estraverse-5.3.0 node_modules/estraverse \
.-esutils-2.0.3 node_modules/esutils \
.-exif-parser-0.1.12 node_modules/exif-parser \
.-extract-zip-2.0.1 node_modules/extract-zip \
.-fast-deep-equal-3.1.3 node_modules/fast-deep-equal \
.-fast-json-stable-stringify-2.1.0 node_modules/fast-json-stable-stringify \
.-fast-levenshtein-2.0.6 node_modules/fast-levenshtein \
.-fastq-1.17.1 node_modules/fastq \
.-fd-slicer-1.1.0 node_modules/fd-slicer \
.-file-entry-cache-6.0.1 node_modules/file-entry-cache \
.-file-type-16.5.4 node_modules/file-type \
.-filelist-1.0.4 node_modules/filelist \
.-fill-range-7.0.1 node_modules/fill-range \
.-find-up-5.0.0 node_modules/find-up \
.-flat-cache-3.2.0 node_modules/flat-cache \
.-flatted-3.3.1 node_modules/flatted \
.-foreground-child-3.1.1 node_modules/foreground-child \
.-form-data-4.0.0 node_modules/form-data \
.-fs-extra-10.1.0 .npm/.-fs-extra-10.1.0 \
.-fs-extra-8.1.0 .npm/.-fs-extra-8.1.0 \
.-fs-extra-9.1.0 .npm/.-fs-extra-9.1.0 \
.-fs-minipass-2.1.0 node_modules/fs-minipass \
.-fs.realpath-1.0.0 node_modules/fs.realpath \
.-function-bind-1.1.2 node_modules/function-bind \
.-get-caller-file-2.0.5 node_modules/get-caller-file \
.-get-intrinsic-1.2.4 node_modules/get-intrinsic \
.-get-stream-5.2.0 node_modules/get-stream \
.-gifwrap-0.10.1 node_modules/gifwrap \
.-glob-10.3.10 .npm/.-glob-10.3.10 \
.-glob-7.2.3 .npm/.-glob-7.2.3 \
.-glob-parent-5.1.2 .npm/.-glob-parent-5.1.2 \
.-glob-parent-6.0.2 .npm/.-glob-parent-6.0.2 \
.-global-4.4.0 node_modules/global \
.-globals-13.24.0 node_modules/globals \
.-gopd-1.0.1 node_modules/gopd \
.-got-11.8.6 node_modules/got \
.-graceful-fs-4.2.11 node_modules/graceful-fs \
.-graphemer-1.4.0 node_modules/graphemer \
.-has-flag-4.0.0 node_modules/has-flag \
.-has-property-descriptors-1.0.2 node_modules/has-property-descriptors \
.-has-proto-1.0.3 node_modules/has-proto \
.-has-symbols-1.0.3 node_modules/has-symbols \
.-hasown-2.0.1 node_modules/hasown \
.-hosted-git-info-4.1.0 node_modules/hosted-git-info \
.-http-cache-semantics-4.1.1 node_modules/http-cache-semantics \
.-http-proxy-agent-5.0.0 node_modules/http-proxy-agent \
.-http2-wrapper-1.0.3 node_modules/http2-wrapper \
.-https-proxy-agent-5.0.1 node_modules/https-proxy-agent \
.-iconv-lite-0.6.3 node_modules/iconv-lite \
.-ieee754-1.2.1 node_modules/ieee754 \
.-ignore-5.3.1 node_modules/ignore \
.-image-q-4.0.0 node_modules/image-q \
.-import-fresh-3.3.0 node_modules/import-fresh \
.-imurmurhash-0.1.4 node_modules/imurmurhash \
.-inflight-1.0.6 node_modules/inflight \
.-inherits-2.0.4 node_modules/inherits \
.-is-binary-path-2.1.0 node_modules/is-binary-path \
.-is-ci-3.0.1 node_modules/is-ci \
.-is-extglob-2.1.1 node_modules/is-extglob \
.-is-fullwidth-code-point-3.0.0 node_modules/is-fullwidth-code-point \
.-is-function-1.0.2 node_modules/is-function \
.-is-glob-4.0.3 node_modules/is-glob \
.-is-number-7.0.0 node_modules/is-number \
.-is-path-inside-3.0.3 node_modules/is-path-inside \
.-is-typedarray-1.0.0 node_modules/is-typedarray \
.-isarray-2.0.5 node_modules/isarray \
.-isbinaryfile-4.0.10 .npm/.-isbinaryfile-4.0.10 \
.-isbinaryfile-5.0.2 .npm/.-isbinaryfile-5.0.2 \
.-isexe-2.0.0 node_modules/isexe \
.-isomorphic-fetch-3.0.0 node_modules/isomorphic-fetch \
.-jackspeak-2.3.6 node_modules/jackspeak \
.-jake-10.8.7 node_modules/jake \
.-jaz-ts-utils-6.3.2 node_modules/jaz-ts-utils \
.-jimp-0.22.12 node_modules/jimp \
.-jpeg-js-0.4.4 node_modules/jpeg-js \
.-js-yaml-4.1.0 node_modules/js-yaml \
.-json-buffer-3.0.1 node_modules/json-buffer \
.-json-schema-traverse-0.4.1 node_modules/json-schema-traverse \
.-json-stable-stringify-1.1.1 node_modules/json-stable-stringify \
.-json-stable-stringify-without-jsonify-1.0.1 node_modules/json-stable-stringify-without-jsonify \
.-json5-2.2.3 node_modules/json5 \
.-jsonfile-4.0.0 .npm/.-jsonfile-4.0.0 \
.-jsonfile-6.1.0 .npm/.-jsonfile-6.1.0 \
.-jsonify-0.0.1 node_modules/jsonify \
.-keyv-4.5.4 node_modules/keyv \
.-kysely-0.25.0 node_modules/kysely \
.-lazy-val-1.0.5 node_modules/lazy-val \
.-levn-0.4.1 node_modules/levn \
.-load-bmfont-1.4.1 node_modules/load-bmfont \
.-locate-path-6.0.0 node_modules/locate-path \
.-lodash-4.17.21 node_modules/lodash \
.-lodash.defaultsdeep-4.6.1 node_modules/lodash.defaultsdeep \
.-lodash.defaultto-4.14.0 node_modules/lodash.defaultto \
.-lodash.escaperegexp-4.1.2 node_modules/lodash.escaperegexp \
.-lodash.flattendeep-4.4.0 node_modules/lodash.flattendeep \
.-lodash.get-4.4.2 node_modules/lodash.get \
.-lodash.has-4.5.2 node_modules/lodash.has \
.-lodash.isempty-4.4.0 node_modules/lodash.isempty \
.-lodash.isequal-4.5.0 node_modules/lodash.isequal \
.-lodash.merge-4.6.2 node_modules/lodash.merge \
.-lodash.negate-3.0.2 node_modules/lodash.negate \
.-lodash.set-4.3.2 node_modules/lodash.set \
.-lodash.unset-4.5.2 node_modules/lodash.unset \
.-lowercase-keys-2.0.0 node_modules/lowercase-keys \
.-lru-cache-10.2.0 .npm/.-lru-cache-10.2.0 \
.-lru-cache-6.0.0 .npm/.-lru-cache-6.0.0 \
.-luaparse-0.3.1 node_modules/luaparse \
.-mime-1.6.0 .npm/.-mime-1.6.0 \
.-mime-2.6.0 .npm/.-mime-2.6.0 \
.-mime-db-1.52.0 node_modules/mime-db \
.-mime-types-2.1.35 node_modules/mime-types \
.-mimic-response-1.0.1 .npm/.-mimic-response-1.0.1 \
.-mimic-response-3.1.0 .npm/.-mimic-response-3.1.0 \
.-min-document-2.19.0 node_modules/min-document \
.-minimatch-3.1.2 .npm/.-minimatch-3.1.2 \
.-minimatch-5.1.6 .npm/.-minimatch-5.1.6 \
.-minimatch-9.0.3 .npm/.-minimatch-9.0.3 \
.-minimist-1.2.8 node_modules/minimist \
.-minipass-3.3.6 .npm/.-minipass-3.3.6 \
.-minipass-5.0.0 .npm/.-minipass-5.0.0 \
.-minizlib-2.1.2 node_modules/minizlib \
.-mkdirp-1.0.4 node_modules/mkdirp \
.-ms-2.0.0 .npm/.-ms-2.0.0 \
.-ms-2.1.2 .npm/.-ms-2.1.2 \
.-natural-compare-1.4.0 node_modules/natural-compare \
.-node-7z-3.0.0 node_modules/node-7z \
.-node-downloader-helper-2.1.9 node_modules/node-downloader-helper \
.-node-fetch-2.7.0 node_modules/node-fetch \
.-node-gzip-1.1.2 node_modules/node-gzip \
.-node-stream-zip-1.15.0 node_modules/node-stream-zip \
.-normalize-path-3.0.0 node_modules/normalize-path \
.-normalize-url-6.1.0 node_modules/normalize-url \
.-object-keys-1.1.1 node_modules/object-keys \
.-omggif-1.0.10 node_modules/omggif \
.-once-1.4.0 node_modules/once \
.-optionator-0.9.3 node_modules/optionator \
.-p-cancelable-2.1.1 node_modules/p-cancelable \
.-p-limit-3.1.0 node_modules/p-limit \
.-p-locate-5.0.0 node_modules/p-locate \
.-pako-1.0.11 node_modules/pako \
.-parent-module-1.0.1 node_modules/parent-module \
.-parse-bmfont-ascii-1.0.6 node_modules/parse-bmfont-ascii \
.-parse-bmfont-binary-1.0.6 node_modules/parse-bmfont-binary \
.-parse-bmfont-xml-1.1.6 node_modules/parse-bmfont-xml \
.-parse-dds-1.2.1 node_modules/parse-dds \
.-parse-headers-2.0.5 node_modules/parse-headers \
.-path-exists-4.0.0 node_modules/path-exists \
.-path-is-absolute-1.0.1 node_modules/path-is-absolute \
.-path-key-3.1.1 node_modules/path-key \
.-path-scurry-1.10.1 node_modules/path-scurry \
.-peek-readable-4.1.0 node_modules/peek-readable \
.-pend-1.2.0 node_modules/pend \
.-phin-2.9.3 node_modules/phin \
.-picomatch-2.3.1 node_modules/picomatch \
.-pixelmatch-4.0.2 node_modules/pixelmatch \
.-plist-3.1.0 node_modules/plist \
.-pngjs-3.4.0 .npm/.-pngjs-3.4.0 \
.-pngjs-6.0.0 .npm/.-pngjs-6.0.0 \
.-prelude-ls-1.2.1 node_modules/prelude-ls \
.-process-0.11.10 node_modules/process \
.-progress-2.0.3 node_modules/progress \
.-promise-retry-2.0.1 node_modules/promise-retry \
.-pump-3.0.0 node_modules/pump \
.-punycode-2.3.1 node_modules/punycode \
.-queue-microtask-1.2.3 node_modules/queue-microtask \
.-quick-lru-5.1.1 node_modules/quick-lru \
.-read-config-file-6.3.2 node_modules/read-config-file \
.-readable-stream-3.6.2 node_modules/readable-stream \
.-readable-web-to-node-stream-3.0.2 node_modules/readable-web-to-node-stream \
.-readdirp-3.6.0 node_modules/readdirp \
.-regenerator-runtime-0.13.11 node_modules/regenerator-runtime \
.-require-directory-2.1.1 node_modules/require-directory \
.-resolve-alpn-1.2.1 node_modules/resolve-alpn \
.-resolve-from-4.0.0 node_modules/resolve-from \
.-responselike-2.0.1 node_modules/responselike \
.-restructure-2.0.1 node_modules/restructure \
.-retry-0.12.0 node_modules/retry \
.-reusify-1.0.4 node_modules/reusify \
.-rimraf-3.0.2 node_modules/rimraf \
.-run-parallel-1.2.0 node_modules/run-parallel \
.-safe-buffer-5.2.1 node_modules/safe-buffer \
.-safer-buffer-2.1.2 node_modules/safer-buffer \
.-sanitize-filename-1.6.3 node_modules/sanitize-filename \
.-sax-1.3.0 node_modules/sax \
.-sdfz-demo-parser-5.11.0 node_modules/sdfz-demo-parser \
.-semver-6.3.1 .npm/.-semver-6.3.1 \
.-semver-7.6.0 .npm/.-semver-7.6.0 \
.-set-function-length-1.2.1 node_modules/set-function-length \
.-shebang-command-2.0.0 node_modules/shebang-command \
.-shebang-regex-3.0.0 node_modules/shebang-regex \
.-signal-exit-3.0.7 .npm/.-signal-exit-3.0.7 \
.-signal-exit-4.1.0 .npm/.-signal-exit-4.1.0 \
.-simple-update-notifier-2.0.0 node_modules/simple-update-notifier \
.-source-map-0.6.1 node_modules/source-map \
.-source-map-support-0.5.21 node_modules/source-map-support \
.-spring-map-parser-6.1.1 node_modules/spring-map-parser \
.-stat-mode-1.0.0 node_modules/stat-mode \
.-string-width-4.2.3 .npm/.-string-width-4.2.3 \
.-string-width-5.1.2 .npm/.-string-width-5.1.2 \
.-string_decoder-1.3.0 node_modules/string_decoder \
.-strip-ansi-6.0.1 .npm/.-strip-ansi-6.0.1 \
.-strip-ansi-7.1.0 .npm/.-strip-ansi-7.1.0 \
.-strip-json-comments-3.1.1 node_modules/strip-json-comments \
.-strtok3-6.3.0 node_modules/strtok3 \
.-sumchecker-3.0.1 node_modules/sumchecker \
.-supports-color-7.2.0 node_modules/supports-color \
.-tar-6.2.0 node_modules/tar \
.-temp-file-3.4.0 node_modules/temp-file \
.-text-table-0.2.0 node_modules/text-table \
.-tga-1.0.7 node_modules/tga \
.-timm-1.7.1 node_modules/timm \
.-tiny-typed-emitter-2.1.0 node_modules/tiny-typed-emitter \
.-tinycolor2-1.6.0 node_modules/tinycolor2 \
.-tmp-0.2.3 node_modules/tmp \
.-tmp-promise-3.0.3 node_modules/tmp-promise \
.-to-regex-range-5.0.1 node_modules/to-regex-range \
.-token-types-4.2.1 node_modules/token-types \
.-tr46-0.0.3 node_modules/tr46 \
.-truncate-utf8-bytes-1.0.2 node_modules/truncate-utf8-bytes \
.-type-check-0.4.0 node_modules/type-check \
.-type-fest-0.20.2 node_modules/type-fest \
.-typedarray-to-buffer-3.1.5 node_modules/typedarray-to-buffer \
.-typescript-5.3.3 node_modules/typescript \
.-undici-types-5.26.5 node_modules/undici-types \
.-universalify-0.1.2 .npm/.-universalify-0.1.2 \
.-universalify-2.0.1 .npm/.-universalify-2.0.1 \
.-uri-js-4.4.1 node_modules/uri-js \
.-utf8-byte-length-1.0.4 node_modules/utf8-byte-length \
.-utif2-4.1.0 node_modules/utif2 \
.-util-deprecate-1.0.2 node_modules/util-deprecate \
.-webidl-conversions-3.0.1 node_modules/webidl-conversions \
.-whatwg-fetch-3.6.20 node_modules/whatwg-fetch \
.-whatwg-url-5.0.0 node_modules/whatwg-url \
.-which-2.0.2 node_modules/which \
.-wrap-ansi-7.0.0 .npm/.-wrap-ansi-7.0.0 \
.-wrap-ansi-8.1.0 .npm/.-wrap-ansi-8.1.0 \
.-wrappy-1.0.2 node_modules/wrappy \
.-write-file-atomic-3.0.3 node_modules/write-file-atomic \
.-ws-7.5.9 node_modules/ws \
.-xhr-2.6.0 node_modules/xhr \
.-xml-parse-from-string-1.0.1 node_modules/xml-parse-from-string \
.-xml2js-0.5.0 node_modules/xml2js \
.-xmlbuilder-11.0.1 .npm/.-xmlbuilder-11.0.1 \
.-xmlbuilder-15.1.1 .npm/.-xmlbuilder-15.1.1 \
.-xtend-4.0.2 node_modules/xtend \
.-y18n-5.0.8 node_modules/y18n \
.-yallist-4.0.0 node_modules/yallist \
.-yargs-17.7.2 node_modules/yargs \
.-yargs-parser-21.1.1 node_modules/yargs-parser \
.-yauzl-2.10.0 node_modules/yauzl \
.-yocto-queue-0.1.0 node_modules/yocto-queue \
@aashutoshrathi-word-wrap-1.2.6 node_modules/@aashutoshrathi/word-wrap \
@develar-schema-utils-2.6.5 node_modules/@develar/schema-utils \
@electron-asar-3.2.8 node_modules/@electron/asar \
@electron-get-2.0.3 node_modules/@electron/get \
@electron-notarize-2.1.0 node_modules/@electron/notarize \
@electron-osx-sign-1.0.5 node_modules/@electron/osx-sign \
@electron-remote-2.1.2 node_modules/@electron/remote \
@electron-universal-1.4.1 node_modules/@electron/universal \
@eslint-community-eslint-utils-4.4.0 node_modules/@eslint-community/eslint-utils \
@eslint-community-regexpp-4.10.0 node_modules/@eslint-community/regexpp \
@eslint-eslintrc-2.1.4 node_modules/@eslint/eslintrc \
@eslint-js-8.57.0 node_modules/@eslint/js \
@humanwhocodes-config-array-0.11.14 node_modules/@humanwhocodes/config-array \
@humanwhocodes-module-importer-1.0.1 node_modules/@humanwhocodes/module-importer \
@humanwhocodes-object-schema-2.0.2 node_modules/@humanwhocodes/object-schema \
@isaacs-cliui-8.0.2 node_modules/@isaacs/cliui \
@jimp-bmp-0.22.12 node_modules/@jimp/bmp \
@jimp-core-0.22.12 node_modules/@jimp/core \
@jimp-custom-0.22.12 node_modules/@jimp/custom \
@jimp-gif-0.22.12 node_modules/@jimp/gif \
@jimp-jpeg-0.22.12 node_modules/@jimp/jpeg \
@jimp-plugin-blit-0.22.12 node_modules/@jimp/plugin-blit \
@jimp-plugin-blur-0.22.12 node_modules/@jimp/plugin-blur \
@jimp-plugin-circle-0.22.12 node_modules/@jimp/plugin-circle \
@jimp-plugin-color-0.22.12 node_modules/@jimp/plugin-color \
@jimp-plugin-contain-0.22.12 node_modules/@jimp/plugin-contain \
@jimp-plugin-cover-0.22.12 node_modules/@jimp/plugin-cover \
@jimp-plugin-crop-0.22.12 node_modules/@jimp/plugin-crop \
@jimp-plugin-displace-0.22.12 node_modules/@jimp/plugin-displace \
@jimp-plugin-dither-0.22.12 node_modules/@jimp/plugin-dither \
@jimp-plugin-fisheye-0.22.12 node_modules/@jimp/plugin-fisheye \
@jimp-plugin-flip-0.22.12 node_modules/@jimp/plugin-flip \
@jimp-plugin-gaussian-0.22.12 node_modules/@jimp/plugin-gaussian \
@jimp-plugin-invert-0.22.12 node_modules/@jimp/plugin-invert \
@jimp-plugin-mask-0.22.12 node_modules/@jimp/plugin-mask \
@jimp-plugin-normalize-0.22.12 node_modules/@jimp/plugin-normalize \
@jimp-plugin-print-0.22.12 node_modules/@jimp/plugin-print \
@jimp-plugin-resize-0.22.12 node_modules/@jimp/plugin-resize \
@jimp-plugin-rotate-0.22.12 node_modules/@jimp/plugin-rotate \
@jimp-plugin-scale-0.22.12 node_modules/@jimp/plugin-scale \
@jimp-plugin-shadow-0.22.12 node_modules/@jimp/plugin-shadow \
@jimp-plugin-threshold-0.22.12 node_modules/@jimp/plugin-threshold \
@jimp-plugins-0.22.12 node_modules/@jimp/plugins \
@jimp-png-0.22.12 node_modules/@jimp/png \
@jimp-tiff-0.22.12 node_modules/@jimp/tiff \
@jimp-types-0.22.12 node_modules/@jimp/types \
@jimp-utils-0.22.12 node_modules/@jimp/utils \
@malept-cross-spawn-promise-1.1.1 node_modules/@malept/cross-spawn-promise \
@malept-flatpak-bundler-0.4.0 node_modules/@malept/flatpak-bundler \
@nodelib-fs.scandir-2.1.5 node_modules/@nodelib/fs.scandir \
@nodelib-fs.stat-2.0.5 node_modules/@nodelib/fs.stat \
@nodelib-fs.walk-1.2.8 node_modules/@nodelib/fs.walk \
@sindresorhus-is-4.6.0 node_modules/@sindresorhus/is \
@szmarczak-http-timer-4.0.6 node_modules/@szmarczak/http-timer \
@tokenizer-token-0.3.0 node_modules/@tokenizer/token \
@tootallnate-once-2.0.0 node_modules/@tootallnate/once \
@types-cacheable-request-6.0.3 node_modules/@types/cacheable-request \
@types-debug-4.1.12 node_modules/@types/debug \
@types-fs-extra-9.0.13 node_modules/@types/fs-extra \
@types-http-cache-semantics-4.0.4 node_modules/@types/http-cache-semantics \
@types-keyv-3.1.4 node_modules/@types/keyv \
@types-ms-0.7.34 node_modules/@types/ms \
@types-node-16.9.1 .npm/@types-node-16.9.1 \
@types-node-20.11.24 .npm/@types-node-20.11.24 \
@types-responselike-1.0.3 node_modules/@types/responselike \
@ungap-structured-clone-1.2.0 node_modules/@ungap/structured-clone \
@xmldom-xmldom-0.8.10 node_modules/@xmldom/xmldom \

MODNPM_CP += \
7zip-bin .npm/.-7zip-bin-5.1.1 \
@electron/asar/node_modules/brace-expansion .npm/.-brace-expansion-1.1.11 \
@electron/asar/node_modules/minimatch .npm/.-minimatch-3.1.2 \
@electron/notarize/node_modules/fs-extra .npm/.-fs-extra-9.1.0 \
@electron/notarize/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
@electron/notarize/node_modules/universalify .npm/.-universalify-2.0.1 \
@electron/osx-sign/node_modules/fs-extra .npm/.-fs-extra-10.1.0 \
@electron/osx-sign/node_modules/isbinaryfile .npm/.-isbinaryfile-4.0.10 \
@electron/osx-sign/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
@electron/osx-sign/node_modules/universalify .npm/.-universalify-2.0.1 \
@electron/universal/node_modules/brace-expansion .npm/.-brace-expansion-1.1.11 \
@electron/universal/node_modules/fs-extra .npm/.-fs-extra-9.1.0 \
@electron/universal/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
@electron/universal/node_modules/minimatch .npm/.-minimatch-3.1.2 \
@electron/universal/node_modules/universalify .npm/.-universalify-2.0.1 \
@eslint/eslintrc/node_modules/brace-expansion .npm/.-brace-expansion-1.1.11 \
@eslint/eslintrc/node_modules/minimatch .npm/.-minimatch-3.1.2 \
@humanwhocodes/config-array/node_modules/brace-expansion .npm/.-brace-expansion-1.1.11 \
@humanwhocodes/config-array/node_modules/minimatch .npm/.-minimatch-3.1.2 \
@isaacs/cliui/node_modules/ansi-regex .npm/.-ansi-regex-6.0.1 \
@isaacs/cliui/node_modules/ansi-styles .npm/.-ansi-styles-6.2.1 \
@isaacs/cliui/node_modules/emoji-regex .npm/.-emoji-regex-9.2.2 \
@isaacs/cliui/node_modules/string-width .npm/.-string-width-5.1.2 \
@isaacs/cliui/node_modules/strip-ansi .npm/.-strip-ansi-7.1.0 \
@isaacs/cliui/node_modules/wrap-ansi .npm/.-wrap-ansi-8.1.0 \
@malept/flatpak-bundler/node_modules/fs-extra .npm/.-fs-extra-9.1.0 \
@malept/flatpak-bundler/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
@malept/flatpak-bundler/node_modules/universalify .npm/.-universalify-2.0.1 \
@types/node .npm/@types-node-20.11.24 \
ansi-regex .npm/.-ansi-regex-5.0.1 \
ansi-styles .npm/.-ansi-styles-4.3.0 \
app-builder-lib/node_modules/fs-extra .npm/.-fs-extra-10.1.0 \
app-builder-lib/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
app-builder-lib/node_modules/semver .npm/.-semver-7.6.0 \
app-builder-lib/node_modules/universalify .npm/.-universalify-2.0.1 \
brace-expansion .npm/.-brace-expansion-2.0.1 \
buffer-equal .npm/.-buffer-equal-1.0.1 \
builder-util/node_modules/7zip-bin .npm/.-7zip-bin-5.2.0 \
builder-util/node_modules/fs-extra .npm/.-fs-extra-10.1.0 \
builder-util/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
builder-util/node_modules/universalify .npm/.-universalify-2.0.1 \
config-file-ts/node_modules/glob .npm/.-glob-10.3.10 \
config-file-ts/node_modules/minimatch .npm/.-minimatch-9.0.3 \
debug .npm/.-debug-4.3.4 \
decompress-response/node_modules/mimic-response .npm/.-mimic-response-3.1.0 \
dir-compare/node_modules/brace-expansion .npm/.-brace-expansion-1.1.11 \
dir-compare/node_modules/minimatch .npm/.-minimatch-3.1.2 \
dmg-builder/node_modules/fs-extra .npm/.-fs-extra-10.1.0 \
dmg-builder/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
dmg-builder/node_modules/universalify .npm/.-universalify-2.0.1 \
electron-builder/node_modules/fs-extra .npm/.-fs-extra-10.1.0 \
electron-builder/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
electron-builder/node_modules/universalify .npm/.-universalify-2.0.1 \
electron-publish/node_modules/fs-extra .npm/.-fs-extra-10.1.0 \
electron-publish/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
electron-publish/node_modules/universalify .npm/.-universalify-2.0.1 \
electron-updater/node_modules/fs-extra .npm/.-fs-extra-10.1.0 \
electron-updater/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
electron-updater/node_modules/semver .npm/.-semver-7.6.0 \
electron-updater/node_modules/universalify .npm/.-universalify-2.0.1 \
emoji-regex .npm/.-emoji-regex-8.0.0 \
eslint/node_modules/brace-expansion .npm/.-brace-expansion-1.1.11 \
eslint/node_modules/glob-parent .npm/.-glob-parent-6.0.2 \
eslint/node_modules/minimatch .npm/.-minimatch-3.1.2 \
foreground-child/node_modules/signal-exit .npm/.-signal-exit-4.1.0 \
fs-extra .npm/.-fs-extra-8.1.0 \
fs-minipass/node_modules/minipass .npm/.-minipass-3.3.6 \
glob .npm/.-glob-7.2.3 \
glob-parent .npm/.-glob-parent-5.1.2 \
glob/node_modules/brace-expansion .npm/.-brace-expansion-1.1.11 \
glob/node_modules/minimatch .npm/.-minimatch-3.1.2 \
image-q/node_modules/@types/node .npm/@types-node-16.9.1 \
isbinaryfile .npm/.-isbinaryfile-5.0.2 \
jake/node_modules/brace-expansion .npm/.-brace-expansion-1.1.11 \
jake/node_modules/minimatch .npm/.-minimatch-3.1.2 \
jsonfile .npm/.-jsonfile-4.0.0 \
load-bmfont/node_modules/buffer-equal .npm/.-buffer-equal-0.0.1 \
load-bmfont/node_modules/mime .npm/.-mime-1.6.0 \
lru-cache .npm/.-lru-cache-6.0.0 \
mime .npm/.-mime-2.6.0 \
mimic-response .npm/.-mimic-response-1.0.1 \
minimatch .npm/.-minimatch-5.1.6 \
minipass .npm/.-minipass-5.0.0 \
minizlib/node_modules/minipass .npm/.-minipass-3.3.6 \
ms .npm/.-ms-2.1.2 \
path-scurry/node_modules/lru-cache .npm/.-lru-cache-10.2.0 \
pixelmatch/node_modules/pngjs .npm/.-pngjs-3.4.0 \
pngjs .npm/.-pngjs-6.0.0 \
semver .npm/.-semver-6.3.1 \
signal-exit .npm/.-signal-exit-3.0.7 \
simple-update-notifier/node_modules/semver .npm/.-semver-7.6.0 \
string-width .npm/.-string-width-4.2.3 \
string-width-cjs .npm/.-string-width-4.2.3 \
strip-ansi .npm/.-strip-ansi-6.0.1 \
strip-ansi-cjs .npm/.-strip-ansi-6.0.1 \
temp-file/node_modules/fs-extra .npm/.-fs-extra-10.1.0 \
temp-file/node_modules/jsonfile .npm/.-jsonfile-6.1.0 \
temp-file/node_modules/universalify .npm/.-universalify-2.0.1 \
tga/node_modules/debug .npm/.-debug-2.6.9 \
tga/node_modules/ms .npm/.-ms-2.0.0 \
universalify .npm/.-universalify-0.1.2 \
wrap-ansi .npm/.-wrap-ansi-7.0.0 \
wrap-ansi-cjs .npm/.-wrap-ansi-7.0.0 \
xml2js/node_modules/xmlbuilder .npm/.-xmlbuilder-11.0.1 \
xmlbuilder .npm/.-xmlbuilder-15.1.1 \

